
package mx.babel.bansefi.banksystem.base.webservices.consultadatosipf;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the mx.babel.bansefi.banksystem.base.webservices.consultadatosipf package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName EJECUTARRESULT_QNAME = new QName(mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_DATOS_REN_IMPSCN_PAG_TRN", "EjecutarResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.babel.bansefi.banksystem.base.webservices.consultadatosipf
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ejecutar }
     *
     */
    public Ejecutar createEjecutar() {
        return new Ejecutar();
    }

    /**
     * Create an instance of {@link ResponseBansefi }
     *
     */
    public ResponseBansefi createResponseBansefi() {
        return new ResponseBansefi();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG createResponseBansefiOTRDATOSRENIMPSCNPAG() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDANAVMSJV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDANAVMSJV createResponseBansefiOTRDATOSRENIMPSCNPAGSTDANAVMSJV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDANAVMSJV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDANAVMSJV.STDANAVMSJLS }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDANAVMSJV.STDANAVMSJLS createResponseBansefiOTRDATOSRENIMPSCNPAGSTDANAVMSJVSTDANAVMSJLS() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDANAVMSJV.STDANAVMSJLS();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE createResponseBansefiOTRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGE() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1 }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1 createResponseBansefiOTRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGETRDATOSRENIMPSCNPAGE() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRDATOSRENIMPSCNPAG }
     *
     */
    public Ejecutar.ITRDATOSRENIMPSCNPAG createEjecutarITRDATOSRENIMPSCNPAG() {
        return new Ejecutar.ITRDATOSRENIMPSCNPAG();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE }
     *
     */
    public Ejecutar.ITRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE createEjecutarITRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGE() {
        return new Ejecutar.ITRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE();
    }

    /**
     * Create an instance of {@link EjecutarResponse }
     *
     */
    public EjecutarResponse createEjecutarResponse() {
        return new EjecutarResponse();
    }

    /**
     * Create an instance of {@link EjecutarResult }
     *
     */
    public EjecutarResult createEjecutarResult() {
        return new EjecutarResult();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDTRNMSJPARMV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDTRNMSJPARMV createResponseBansefiOTRDATOSRENIMPSCNPAGSTDTRNMSJPARMV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDTRNMSJPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDTRNOPARMV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDTRNOPARMV createResponseBansefiOTRDATOSRENIMPSCNPAGSTDTRNOPARMV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDTRNOPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDANAVMSJV.ANNUMANOTACIONESV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDANAVMSJV.ANNUMANOTACIONESV createResponseBansefiOTRDATOSRENIMPSCNPAGSTDANAVMSJVANNUMANOTACIONESV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDANAVMSJV.ANNUMANOTACIONESV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDANAVMSJV.STDANAVMSJLS.DESCRIPANTCNV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDANAVMSJV.STDANAVMSJLS.DESCRIPANTCNV createResponseBansefiOTRDATOSRENIMPSCNPAGSTDANAVMSJVSTDANAVMSJLSDESCRIPANTCNV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDANAVMSJV.STDANAVMSJLS.DESCRIPANTCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDANAVMSJV.STDANAVMSJLS.DESCINDPRDADV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDANAVMSJV.STDANAVMSJLS.DESCINDPRDADV createResponseBansefiOTRDATOSRENIMPSCNPAGSTDANAVMSJVSTDANAVMSJLSDESCINDPRDADV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDANAVMSJV.STDANAVMSJLS.DESCINDPRDADV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDANAVMSJV.STDANAVMSJLS.STDDESCRCANTCNV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDANAVMSJV.STDANAVMSJLS.STDDESCRCANTCNV createResponseBansefiOTRDATOSRENIMPSCNPAGSTDANAVMSJVSTDANAVMSJLSSTDDESCRCANTCNV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.STDANAVMSJV.STDANAVMSJLS.STDDESCRCANTCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.IPMONEDAV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.IPMONEDAV createResponseBansefiOTRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGEIPMONEDAV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.IPMONEDAV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.IPFULTLIQV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.IPFULTLIQV createResponseBansefiOTRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGEIPFULTLIQV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.IPFULTLIQV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.PSVCCCV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.PSVCCCV createResponseBansefiOTRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGEPSVCCCV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.PSVCCCV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.IPDATOSCONDV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.IPDATOSCONDV createResponseBansefiOTRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGETRDATOSRENIMPSCNPAGEIPDATOSCONDV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.IPDATOSCONDV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSESTRCTVLISTAV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSESTRCTVLISTAV createResponseBansefiOTRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGETRDATOSRENIMPSCNPAGEKSESTRCTVLISTAV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSESTRCTVLISTAV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSKSRLPKDOMV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSKSRLPKDOMV createResponseBansefiOTRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGETRDATOSRENIMPSCNPAGEKSKSRLPKDOMV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSKSRLPKDOMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSESTRCTRNGV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSESTRCTRNGV createResponseBansefiOTRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGETRDATOSRENIMPSCNPAGEKSESTRCTRNGV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSESTRCTRNGV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSESTRCTVRNGV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSESTRCTVRNGV createResponseBansefiOTRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGETRDATOSRENIMPSCNPAGEKSESTRCTVRNGV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSESTRCTVRNGV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSESTRCTCMSN1V }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSESTRCTCMSN1V createResponseBansefiOTRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGETRDATOSRENIMPSCNPAGEKSESTRCTCMSN1V() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSESTRCTCMSN1V();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSCMSNPRCTLV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSCMSNPRCTLV createResponseBansefiOTRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGETRDATOSRENIMPSCNPAGEKSCMSNPRCTLV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSCMSNPRCTLV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSCMSNFIJV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSCMSNFIJV createResponseBansefiOTRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGETRDATOSRENIMPSCNPAGEKSCMSNFIJV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSCMSNFIJV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSESTRCTINT1V }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSESTRCTINT1V createResponseBansefiOTRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGETRDATOSRENIMPSCNPAGEKSESTRCTINT1V() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSESTRCTINT1V();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSESTRCTINTFIJV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSESTRCTINTFIJV createResponseBansefiOTRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGETRDATOSRENIMPSCNPAGEKSESTRCTINTFIJV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSESTRCTINTFIJV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSESTRCTINTVARV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSESTRCTINTVARV createResponseBansefiOTRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGETRDATOSRENIMPSCNPAGEKSESTRCTINTVARV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSESTRCTINTVARV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSINTFRANQ1V }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSINTFRANQ1V createResponseBansefiOTRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGETRDATOSRENIMPSCNPAGEKSINTFRANQ1V() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSINTFRANQ1V();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSINTFRANQFIJV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSINTFRANQFIJV createResponseBansefiOTRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGETRDATOSRENIMPSCNPAGEKSINTFRANQFIJV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSINTFRANQFIJV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSINTFRANQVARV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSINTFRANQVARV createResponseBansefiOTRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGETRDATOSRENIMPSCNPAGEKSINTFRANQVARV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSINTFRANQVARV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSINTRLSPV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSINTRLSPV createResponseBansefiOTRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGETRDATOSRENIMPSCNPAGEKSINTRLSPV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSINTRLSPV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSMATRIZV }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSMATRIZV createResponseBansefiOTRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGETRDATOSRENIMPSCNPAGEKSMATRIZV() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.KSMATRIZV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.IDCCPS1V }
     *
     */
    public ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.IDCCPS1V createResponseBansefiOTRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGETRDATOSRENIMPSCNPAGEIDCCPS1V() {
        return new ResponseBansefi.OTRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.TRDATOSRENIMPSCNPAGE1.IDCCPS1V();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRDATOSRENIMPSCNPAG.STDTRNIPARMV }
     *
     */
    public Ejecutar.ITRDATOSRENIMPSCNPAG.STDTRNIPARMV createEjecutarITRDATOSRENIMPSCNPAGSTDTRNIPARMV() {
        return new Ejecutar.ITRDATOSRENIMPSCNPAG.STDTRNIPARMV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.IPIMPSCNP }
     *
     */
    public Ejecutar.ITRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.IPIMPSCNP createEjecutarITRDATOSRENIMPSCNPAGTRDATOSRENIMPSCNPAGEIPIMPSCNP() {
        return new Ejecutar.ITRDATOSRENIMPSCNPAG.TRDATOSRENIMPSCNPAGE.IPIMPSCNP();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EjecutarResult }{@code >}}
     *
     */
    @XmlElementDecl(namespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_DATOS_REN_IMPSCN_PAG_TRN", name = "EjecutarResult")
    public JAXBElement<EjecutarResult> createEjecutarResult(final EjecutarResult value) {
        return new JAXBElement<EjecutarResult>(EJECUTARRESULT_QNAME, EjecutarResult.class, null, value);
    }

}
