package mx.babel.bansefi.banksystem.cajas.webservice.ajustaexistencias;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2015-11-27T12:48:27.789-06:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebService(targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_AJUSTE_DESGLS_EX_TRN", name = "SoapPort")
@XmlSeeAlso({ObjectFactory.class})
public interface SoapPort {

    @WebResult(name = "EjecutarResult", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_AJUSTE_DESGLS_EX_TRN")
    @RequestWrapper(localName = "Ejecutar", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_AJUSTE_DESGLS_EX_TRN", className = "mx.babel.bansefi.banksystem.cajas.webservice.ajustaexistencias.Ejecutar")
    @WebMethod(operationName = "Ejecutar", action = "http://BansefiNSS/WebServicesNSS/TR_AJUSTE_DESGLS_EX_TRN/Ejecutar")
    @ResponseWrapper(localName = "EjecutarResponse", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_AJUSTE_DESGLS_EX_TRN", className = "mx.babel.bansefi.banksystem.cajas.webservice.ajustaexistencias.EjecutarResponse")
    public mx.babel.bansefi.banksystem.cajas.webservice.ajustaexistencias.EjecutarResult ejecutar(
        @WebParam(name = "USERHEADER", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_AJUSTE_DESGLS_EX_TRN")
        java.lang.String userheader,
        @WebParam(name = "PASSHEADER", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_AJUSTE_DESGLS_EX_TRN")
        java.lang.String passheader,
        @WebParam(name = "IPHEADER", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_AJUSTE_DESGLS_EX_TRN")
        java.lang.String ipheader,
        @WebParam(name = "ITR_AJUSTE_DESGLS_EX_TRN", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_AJUSTE_DESGLS_EX_TRN")
        mx.babel.bansefi.banksystem.cajas.webservice.ajustaexistencias.Ejecutar.ITRAJUSTEDESGLSEXTRN itrAJUSTEDESGLSEXTRN
    );
}
