
package mx.babel.bansefi.banksystem.base.webservices.consultacuenta;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bansefinss.webservicesnss.tr_consulta_acuerdo_trn package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName EJECUTAR_RESULT_QNAME = new QName(mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_CONSULTA_ACUERDO_TRN", "EjecutarResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bansefinss.webservicesnss.tr_consulta_acuerdo_trn
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ejecutar }
     * 
     */
    public Ejecutar createEjecutar() {
        return new Ejecutar();
    }

    /**
     * Create an instance of {@link ResponseBansefi }
     * 
     */
    public ResponseBansefi createResponseBansefi() {
        return new ResponseBansefi();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN createResponseBansefiOTRCONSULTAACUERDOTRN() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.STDANAVMSJV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.STDANAVMSJV createResponseBansefiOTRCONSULTAACUERDOTRNSTDANAVMSJV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.STDANAVMSJV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.STDANAVMSJV.STDANAVMSJLS }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.STDANAVMSJV.STDANAVMSJLS createResponseBansefiOTRCONSULTAACUERDOTRNSTDANAVMSJVSTDANAVMSJLS() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.STDANAVMSJV.STDANAVMSJLS();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZ() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZ() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1V() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRCONSULTAACUERDOTRN }
     * 
     */
    public Ejecutar.ITRCONSULTAACUERDOTRN createEjecutarITRCONSULTAACUERDOTRN() {
        return new Ejecutar.ITRCONSULTAACUERDOTRN();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTY }
     * 
     */
    public Ejecutar.ITRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTY createEjecutarITRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTY() {
        return new Ejecutar.ITRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTY();
    }

    /**
     * Create an instance of {@link EjecutarResponse }
     * 
     */
    public EjecutarResponse createEjecutarResponse() {
        return new EjecutarResponse();
    }

    /**
     * Create an instance of {@link EjecutarResult }
     * 
     */
    public EjecutarResult createEjecutarResult() {
        return new EjecutarResult();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.STDTRNMSJPARMV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.STDTRNMSJPARMV createResponseBansefiOTRCONSULTAACUERDOTRNSTDTRNMSJPARMV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.STDTRNMSJPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.STDTRNOPARMV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.STDTRNOPARMV createResponseBansefiOTRCONSULTAACUERDOTRNSTDTRNOPARMV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.STDTRNOPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.STDANAVMSJV.ANNUMANOTACIONESV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.STDANAVMSJV.ANNUMANOTACIONESV createResponseBansefiOTRCONSULTAACUERDOTRNSTDANAVMSJVANNUMANOTACIONESV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.STDANAVMSJV.ANNUMANOTACIONESV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.STDANAVMSJV.STDANAVMSJLS.DESCRIPANTCNV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.STDANAVMSJV.STDANAVMSJLS.DESCRIPANTCNV createResponseBansefiOTRCONSULTAACUERDOTRNSTDANAVMSJVSTDANAVMSJLSDESCRIPANTCNV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.STDANAVMSJV.STDANAVMSJLS.DESCRIPANTCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.STDANAVMSJV.STDANAVMSJLS.DESCINDPRDADV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.STDANAVMSJV.STDANAVMSJLS.DESCINDPRDADV createResponseBansefiOTRCONSULTAACUERDOTRNSTDANAVMSJVSTDANAVMSJLSDESCINDPRDADV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.STDANAVMSJV.STDANAVMSJLS.DESCINDPRDADV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.STDANAVMSJV.STDANAVMSJLS.STDDESCRCANTCNV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.STDANAVMSJV.STDANAVMSJLS.STDDESCRCANTCNV createResponseBansefiOTRCONSULTAACUERDOTRNSTDANAVMSJVSTDANAVMSJLSSTDDESCRCANTCNV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.STDANAVMSJV.STDANAVMSJLS.STDDESCRCANTCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.ACACE }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.ACACE createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZACACE() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.ACACE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.INDREPRESENTANTEV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.INDREPRESENTANTEV createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZINDREPRESENTANTEV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.INDREPRESENTANTEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.DESCRPDVV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.DESCRPDVV createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZDESCRPDVV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.DESCRPDVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.PERSONAACV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.PERSONAACV createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZPERSONAACV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.PERSONAACV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.NUMTARJETAV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.NUMTARJETAV createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZNUMTARJETAV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.NUMTARJETAV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KACDACE }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KACDACE createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKACDACE() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KACDACE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTVLISTAV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTVLISTAV createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAESTRCTVLISTAV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTVLISTAV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAKARLPKDOMV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAKARLPKDOMV createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAKARLPKDOMV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAKARLPKDOMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTRNGV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTRNGV createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAESTRCTRNGV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTRNGV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTVRNGV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTVRNGV createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAESTRCTVRNGV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTVRNGV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTCMSN1V }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTCMSN1V createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAESTRCTCMSN1V() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTCMSN1V();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KACMSNPRCTLV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KACMSNPRCTLV createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKACMSNPRCTLV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KACMSNPRCTLV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KACMSNFIJV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KACMSNFIJV createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKACMSNFIJV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KACMSNFIJV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTINT1V }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTINT1V createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAESTRCTINT1V() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTINT1V();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTINTFIJV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTINTFIJV createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAESTRCTINTFIJV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTINTFIJV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTINTVARV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTINTVARV createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAESTRCTINTVARV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTINTVARV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTFRANQ1V }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTFRANQ1V createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAINTFRANQ1V() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTFRANQ1V();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTFRANQFIJV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTFRANQFIJV createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAINTFRANQFIJV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTFRANQFIJV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTFRANQVARV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTFRANQVARV createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAINTFRANQVARV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTFRANQVARV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTRLSPV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTRLSPV createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAINTRLSPV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTRLSPV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAMATRIZV }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAMATRIZV createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAMATRIZV() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAMATRIZV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.IDCCPS1V }
     * 
     */
    public ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.IDCCPS1V createResponseBansefiOTRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VIDCCPS1V() {
        return new ResponseBansefi.OTRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.IDCCPS1V();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRCONSULTAACUERDOTRN.STDTRNIPARMV }
     * 
     */
    public Ejecutar.ITRCONSULTAACUERDOTRN.STDTRNIPARMV createEjecutarITRCONSULTAACUERDOTRNSTDTRNIPARMV() {
        return new Ejecutar.ITRCONSULTAACUERDOTRN.STDTRNIPARMV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTY.ACACP }
     * 
     */
    public Ejecutar.ITRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTY.ACACP createEjecutarITRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTYACACP() {
        return new Ejecutar.ITRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTY.ACACP();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTY.ACINDCONSUACV }
     * 
     */
    public Ejecutar.ITRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTY.ACINDCONSUACV createEjecutarITRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTYACINDCONSUACV() {
        return new Ejecutar.ITRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTY.ACINDCONSUACV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTY.ACINDPROCEDEGESTIONV }
     * 
     */
    public Ejecutar.ITRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTY.ACINDPROCEDEGESTIONV createEjecutarITRCONSULTAACUERDOTRNTRCONSULTAACUERDOEVTYACINDPROCEDEGESTIONV() {
        return new Ejecutar.ITRCONSULTAACUERDOTRN.TRCONSULTAACUERDOEVTY.ACINDPROCEDEGESTIONV();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EjecutarResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_CONSULTA_ACUERDO_TRN", name = "EjecutarResult")
    public JAXBElement<EjecutarResult> createEjecutarResult(EjecutarResult value) {
        return new JAXBElement<EjecutarResult>(EJECUTAR_RESULT_QNAME, EjecutarResult.class, null, value);
    }

}
