
package mx.babel.bansefi.banksystem.cuentas.webservices.simulacioncancelacioncuenta;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.babel.bansefi.banksystem.cuentas.webservices.simulacioncancelacioncuenta package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EjecutarResult_QNAME = new QName(mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_SIMUL_AC_TRN", "EjecutarResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.babel.bansefi.banksystem.cuentas.webservices.simulacioncancelacioncuenta
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ejecutar }
     * 
     */
    public Ejecutar createEjecutar() {
        return new Ejecutar();
    }

    /**
     * Create an instance of {@link ResponseBansefi }
     * 
     */
    public ResponseBansefi createResponseBansefi() {
        return new ResponseBansefi();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO createResponseBansefiTRSIMULACTRNO() {
        return new ResponseBansefi.TRSIMULACTRNO();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZ() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.GACRESULTOPERV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.GACRESULTOPERV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVGACRESULTOPERV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.GACRESULTOPERV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVGTOSNOTARIOV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVGTOSNOTARIOV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVGTOSNOTARIOV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVGTOSNOTARIOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLSUBVV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVACVACPSVCONVV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLINTERESV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLINTERESVLIQHLTRAMOAPLICV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLCOMISIONV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLCOMISIONVLIQAFAPNTECMSNLST() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLCOMISIONVLIQAFAPNTECMSNLSTLIQAFAPNTECMSNE() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.IDFRLINEAAVALV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.IDFRLINEAAVALV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVIDFRLINEAAVALV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.IDFRLINEAAVALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVIDFRACASOCCV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVIDFRACASOCCV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVIDFRACASOCCV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVIDFRACASOCCV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVAFCONSTITV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVAFCONSTITV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVAFCONSTITV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVAFCONSTITV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVIMPTESDIVISIONV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLSDOOPCIONV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLSDOOPCIONV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVHLSDOOPCIONV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLSDOOPCIONV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLSDOOPCIONV.HLSDOLST }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLSDOOPCIONV.HLSDOLST createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVHLSDOOPCIONVHLSDOLST() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLSDOOPCIONV.HLSDOLST();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLHCOLIQEV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLHCOLIQEV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVHLHCOLIQEV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLHCOLIQEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLINFADICLST }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLINFADICLST createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVHLHCOLIQEVHLINFADICLST() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLINFADICLST();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLSDOLST }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLSDOLST createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVHLHCOLIQEVHLSDOLST() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLSDOLST();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.GACRESULTOPERV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.GACRESULTOPERV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVGACRESULTOPERV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.GACRESULTOPERV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLSUBVV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVACPSVCONVV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLINTERESV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLINTERESVLIQHLTRAMOAPLICV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLCOMISIONV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLCOMISIONVLIQAFAPNTECMSNLST() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLCOMISIONVLIQAFAPNTECMSNLSTLIQAFAPNTECMSNE() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVIDFRACASOCCV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.IDFRLINEAAVALV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.IDFRLINEAAVALV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVIDFRLINEAAVALV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.IDFRLINEAAVALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLSDOOPCIONV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLSDOOPCIONV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVHLSDOOPCIONV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLSDOOPCIONV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLSDOOPCIONV.HLSDOLST }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLSDOOPCIONV.HLSDOLST createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVHLSDOOPCIONVHLSDOLST() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLSDOOPCIONV.HLSDOLST();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLHCOLIQEV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLHCOLIQEV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVHLHCOLIQEV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLHCOLIQEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLINFADICLST }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLINFADICLST createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVHLHCOLIQEVHLINFADICLST() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLINFADICLST();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLSDOLST }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLSDOLST createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVHLHCOLIQEVHLSDOLST() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLSDOLST();
    }

    /**
     * Create an instance of {@link Ejecutar.TRSIMULACTRNI }
     * 
     */
    public Ejecutar.TRSIMULACTRNI createEjecutarTRSIMULACTRNI() {
        return new Ejecutar.TRSIMULACTRNI();
    }

    /**
     * Create an instance of {@link Ejecutar.TRSIMULACTRNI.TRSIMULACEVTY }
     * 
     */
    public Ejecutar.TRSIMULACTRNI.TRSIMULACEVTY createEjecutarTRSIMULACTRNITRSIMULACEVTY() {
        return new Ejecutar.TRSIMULACTRNI.TRSIMULACEVTY();
    }

    /**
     * Create an instance of {@link EjecutarResponse }
     * 
     */
    public EjecutarResponse createEjecutarResponse() {
        return new EjecutarResponse();
    }

    /**
     * Create an instance of {@link EjecutarResult }
     * 
     */
    public EjecutarResult createEjecutarResult() {
        return new EjecutarResult();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.STDTRNMSJPARMV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.STDTRNMSJPARMV createResponseBansefiTRSIMULACTRNOSTDTRNMSJPARMV() {
        return new ResponseBansefi.TRSIMULACTRNO.STDTRNMSJPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.STDTRNOPARMV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.STDTRNOPARMV createResponseBansefiTRSIMULACTRNOSTDTRNOPARMV() {
        return new ResponseBansefi.TRSIMULACTRNO.STDTRNOPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.ACACE }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.ACACE createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZACACE() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.ACACE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVIMPTOTALV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVIMPTOTALV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVIMPTOTALV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVIMPTOTALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVIMPDISPOV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVIMPDISPOV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVIMPDISPOV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVIMPDISPOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACACSUSTITUIDOV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACACSUSTITUIDOV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACACSUSTITUIDOV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACACSUSTITUIDOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.AIACRLBIE }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.AIACRLBIE createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVAIACRLBIE() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.AIACRLBIE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVINDMIXTOV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVINDMIXTOV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVINDMIXTOV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVINDMIXTOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVINDSUBVENCV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVINDSUBVENCV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVINDSUBVENCV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVINDSUBVENCV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVINDSUBDIVV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVINDSUBDIVV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVINDSUBDIVV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVINDSUBDIVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVPERIODLIQUIDV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVPERIODLIQUIDV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVPERIODLIQUIDV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVPERIODLIQUIDV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDISPONIBILIDADV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDISPONIBILIDADV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDISPONIBILIDADV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDISPONIBILIDADV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVMODALLIQUIDV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVMODALLIQUIDV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVMODALLIQUIDV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVMODALLIQUIDV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVFCHPROXLIQUIV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVFCHPROXLIQUIV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVFCHPROXLIQUIV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVFCHPROXLIQUIV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVCUOTAACTUALV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVCUOTAACTUALV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVCUOTAACTUALV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVCUOTAACTUALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVCAPITALCTV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVCAPITALCTV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVCAPITALCTV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVCAPITALCTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVENTREGAINICIALV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVENTREGAINICIALV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVENTREGAINICIALV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVENTREGAINICIALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVVALORRESIDUALV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVVALORRESIDUALV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVVALORRESIDUALV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVVALORRESIDUALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVINDDOMICV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVINDDOMICV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVINDDOMICV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVINDDOMICV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.GACRESULTOPERV.GACIMPTENETOV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.GACRESULTOPERV.GACIMPTENETOV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVGACRESULTOPERVGACIMPTENETOV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.GACRESULTOPERV.GACIMPTENETOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.GACRESULTOPERV.GACIMPTEOPERV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.GACRESULTOPERV.GACIMPTEOPERV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVGACRESULTOPERVGACIMPTEOPERV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.GACRESULTOPERV.GACIMPTEOPERV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVGTOSNOTARIOV.AFAPNTEE }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVGTOSNOTARIOV.AFAPNTEE createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVGTOSNOTARIOVAFAPNTEE() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVGTOSNOTARIOV.AFAPNTEE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVTOTALSUBDOV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVTOTALSUBDOV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLSUBVVACVTOTALSUBDOV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVTOTALSUBDOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.IDFRSBLV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.IDFRSBLV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVIDFRSBLV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.IDFRSBLV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINTERESSUBVCNV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINTERESSUBVCNV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVACVINTERESSUBVCNV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINTERESSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCAPITALSUBVCNV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCAPITALSUBVCNV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVACVCAPITALSUBVCNV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCAPITALSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFINNCSUBVCNV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFINNCSUBVCNV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVACVFINNCSUBVCNV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFINNCSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMASUBVCNV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMASUBVCNV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVACVFORMASUBVCNV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMASUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCPTOSUBVCNV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCPTOSUBVCNV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVACVCPTOSUBVCNV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCPTOSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCOBROANTV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCOBROANTV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVACVCOBROANTV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCOBROANTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINFORMASUBVCNV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINFORMASUBVCNV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVACVINFORMASUBVCNV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINFORMASUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMARECLAMV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMARECLAMV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVACVFORMARECLAMV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMARECLAMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVSUBVRECLAMABLEV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVSUBVRECLAMABLEV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVACVSUBVRECLAMABLEV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVSUBVRECLAMABLEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV.ACACP }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV.ACACP createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVACVACPSVCONVVACACP() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV.ACACP();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV.ACVINTERESCTV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV.ACVINTERESCTV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLINTERESVACVINTERESCTV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV.ACVINTERESCTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV.HLTRAMOV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV.HLTRAMOV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLINTERESVLIQHLTRAMOAPLICVHLTRAMOV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV.HLTRAMOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVGASTOSV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVGASTOSV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLCOMISIONVACVGASTOSV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVGASTOSV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVTOTALGASEXTV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVTOTALGASEXTV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLCOMISIONVACVTOTALGASEXTV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVTOTALGASEXTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVCOMISIONV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVCOMISIONV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLCOMISIONVACVCOMISIONV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVCOMISIONV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVIMPUESTOV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVIMPUESTOV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLCOMISIONVACVIMPUESTOV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVIMPUESTOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE.LIQKTCMSNV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE.LIQKTCMSNV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVDSGLCOMISIONVLIQAFAPNTECMSNLSTLIQAFAPNTECMSNELIQKTCMSNV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE.LIQKTCMSNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.IDFRLINEAAVALV.IDFRACLV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.IDFRLINEAAVALV.IDFRACLV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVIDFRLINEAAVALVIDFRACLV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.IDFRLINEAAVALV.IDFRACLV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVIDFRACASOCCV.IDFRACLV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVIDFRACASOCCV.IDFRACLV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVIDFRACASOCCVIDFRACLV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVIDFRACASOCCV.IDFRACLV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVIDFRACASOCCV.ACVMONEDAASOCCV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVIDFRACASOCCV.ACVMONEDAASOCCV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVIDFRACASOCCVACVMONEDAASOCCV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVIDFRACASOCCV.ACVMONEDAASOCCV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVAFCONSTITV.AFAPNTEE }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVAFCONSTITV.AFAPNTEE createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVACVAFCONSTITVAFAPNTEE() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.ACVAFCONSTITV.AFAPNTEE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV.ACVDISPBLESUBDVV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV.ACVDISPBLESUBDVV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVIMPTESDIVISIONVACVDISPBLESUBDVV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV.ACVDISPBLESUBDVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV.ACVLIMITESUBDVV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV.ACVLIMITESUBDVV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVIMPTESDIVISIONVACVLIMITESUBDVV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV.ACVLIMITESUBDVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV.AMORTIZSUBDVV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV.AMORTIZSUBDVV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVIMPTESDIVISIONVAMORTIZSUBDVV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV.AMORTIZSUBDVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLSDOOPCIONV.HLSDOLST.HLSDOEV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLSDOOPCIONV.HLSDOLST.HLSDOEV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVHLSDOOPCIONVHLSDOLSTHLSDOEV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLSDOOPCIONV.HLSDOLST.HLSDOEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLHCOLIQE }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLHCOLIQE createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVHLHCOLIQEVHLHCOLIQE() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLHCOLIQE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLINFADICLST.HLINFADICV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLINFADICLST.HLINFADICV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVHLHCOLIQEVHLINFADICLSTHLINFADICV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLINFADICLST.HLINFADICV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLSDOLST.HLSDOEV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLSDOLST.HLSDOEV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCONSTVHLHCOLIQEVHLSDOLSTHLSDOEV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLSDOLST.HLSDOEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVIMPTOTALV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVIMPTOTALV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVIMPTOTALV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVIMPTOTALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVSDORSGOAVV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVSDORSGOAVV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVSDORSGOAVV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVSDORSGOAVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVSDOPDTEVTOV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVSDOPDTEVTOV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVSDOPDTEVTOV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVSDOPDTEVTOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVIMPLIMV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVIMPLIMV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVIMPLIMV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVIMPLIMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVIMPDEUDAIMPAGV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVIMPDEUDAIMPAGV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVIMPDEUDAIMPAGV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVIMPDEUDAIMPAGV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVINDSUBVENCV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVINDSUBVENCV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVINDSUBVENCV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVINDSUBVENCV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVINDSUBDIVV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVINDSUBDIVV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVINDSUBDIVV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVINDSUBDIVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVINDMIXTOV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVINDMIXTOV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVINDMIXTOV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVINDMIXTOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVAFAPUNTESV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVAFAPUNTESV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVAFAPUNTESV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVAFAPUNTESV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACLINEAGRUPOV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACLINEAGRUPOV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACLINEAGRUPOV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACLINEAGRUPOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVMODALLIQUIDV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVMODALLIQUIDV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVMODALLIQUIDV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVMODALLIQUIDV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVINDDOMICV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVINDDOMICV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVINDDOMICV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVINDDOMICV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.GACRESULTOPERV.GACIMPTENETOV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.GACRESULTOPERV.GACIMPTENETOV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVGACRESULTOPERVGACIMPTENETOV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.GACRESULTOPERV.GACIMPTENETOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.GACRESULTOPERV.GACIMPTEOPERV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.GACRESULTOPERV.GACIMPTEOPERV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVGACRESULTOPERVGACIMPTEOPERV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.GACRESULTOPERV.GACIMPTEOPERV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVTOTALSUBDOV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVTOTALSUBDOV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLSUBVVACVTOTALSUBDOV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVTOTALSUBDOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.IDFRSBLV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.IDFRSBLV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVIDFRSBLV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.IDFRSBLV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINTERESSUBVCNV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINTERESSUBVCNV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVINTERESSUBVCNV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINTERESSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCAPITALSUBVCNV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCAPITALSUBVCNV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVCAPITALSUBVCNV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCAPITALSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFINNCSUBVCNV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFINNCSUBVCNV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVFINNCSUBVCNV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFINNCSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMASUBVCNV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMASUBVCNV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVFORMASUBVCNV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMASUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCPTOSUBVCNV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCPTOSUBVCNV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVCPTOSUBVCNV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCPTOSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCOBROANTV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCOBROANTV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVCOBROANTV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCOBROANTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINFORMASUBVCNV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINFORMASUBVCNV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVINFORMASUBVCNV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINFORMASUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMARECLAMV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMARECLAMV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVFORMARECLAMV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMARECLAMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVSUBVRECLAMABLEV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVSUBVRECLAMABLEV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVSUBVRECLAMABLEV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVSUBVRECLAMABLEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV.ACACP }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV.ACACP createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVACPSVCONVVACACP() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV.ACACP();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.ACVINTERESCTV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.ACVINTERESCTV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLINTERESVACVINTERESCTV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.ACVINTERESCTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV.HLTRAMOV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV.HLTRAMOV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLINTERESVLIQHLTRAMOAPLICVHLTRAMOV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV.HLTRAMOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVGASTOSV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVGASTOSV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLCOMISIONVACVGASTOSV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVGASTOSV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVTOTALGASEXTV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVTOTALGASEXTV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLCOMISIONVACVTOTALGASEXTV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVTOTALGASEXTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVCOMISIONV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVCOMISIONV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLCOMISIONVACVCOMISIONV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVCOMISIONV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVIMPUESTOV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVIMPUESTOV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLCOMISIONVACVIMPUESTOV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVIMPUESTOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE.LIQKTCMSNV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE.LIQKTCMSNV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVDSGLCOMISIONVLIQAFAPNTECMSNLSTLIQAFAPNTECMSNELIQKTCMSNV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE.LIQKTCMSNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV.IDFRACLV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV.IDFRACLV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVIDFRACASOCCVIDFRACLV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV.IDFRACLV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV.ACVMONEDAASOCCV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV.ACVMONEDAASOCCV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVACVIDFRACASOCCVACVMONEDAASOCCV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV.ACVMONEDAASOCCV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.IDFRLINEAAVALV.IDFRACLV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.IDFRLINEAAVALV.IDFRACLV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVIDFRLINEAAVALVIDFRACLV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.IDFRLINEAAVALV.IDFRACLV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLSDOOPCIONV.HLSDOLST.HLSDOEV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLSDOOPCIONV.HLSDOLST.HLSDOEV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVHLSDOOPCIONVHLSDOLSTHLSDOEV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLSDOOPCIONV.HLSDOLST.HLSDOEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLHCOLIQE }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLHCOLIQE createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVHLHCOLIQEVHLHCOLIQE() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLHCOLIQE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLINFADICLST.HLINFADICV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLINFADICLST.HLINFADICV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVHLHCOLIQEVHLINFADICLSTHLINFADICV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLINFADICLST.HLINFADICV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLSDOLST.HLSDOEV }
     * 
     */
    public ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLSDOLST.HLSDOEV createResponseBansefiTRSIMULACTRNOTRSIMULACEVTZTRSIMULCANCVHLHCOLIQEVHLSDOLSTHLSDOEV() {
        return new ResponseBansefi.TRSIMULACTRNO.TRSIMULACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLSDOLST.HLSDOEV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRSIMULACTRNI.STDTRNIPARMV }
     * 
     */
    public Ejecutar.TRSIMULACTRNI.STDTRNIPARMV createEjecutarTRSIMULACTRNISTDTRNIPARMV() {
        return new Ejecutar.TRSIMULACTRNI.STDTRNIPARMV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRSIMULACTRNI.TRSIMULACEVTY.ACACP }
     * 
     */
    public Ejecutar.TRSIMULACTRNI.TRSIMULACEVTY.ACACP createEjecutarTRSIMULACTRNITRSIMULACEVTYACACP() {
        return new Ejecutar.TRSIMULACTRNI.TRSIMULACEVTY.ACACP();
    }

    /**
     * Create an instance of {@link Ejecutar.TRSIMULACTRNI.TRSIMULACEVTY.FECHAV }
     * 
     */
    public Ejecutar.TRSIMULACTRNI.TRSIMULACEVTY.FECHAV createEjecutarTRSIMULACTRNITRSIMULACEVTYFECHAV() {
        return new Ejecutar.TRSIMULACTRNI.TRSIMULACEVTY.FECHAV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRSIMULACTRNI.TRSIMULACEVTY.ACCUADROIRREGV }
     * 
     */
    public Ejecutar.TRSIMULACTRNI.TRSIMULACEVTY.ACCUADROIRREGV createEjecutarTRSIMULACTRNITRSIMULACEVTYACCUADROIRREGV() {
        return new Ejecutar.TRSIMULACTRNI.TRSIMULACEVTY.ACCUADROIRREGV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRSIMULACTRNI.TRSIMULACEVTY.ACVTIPOCOBROV }
     * 
     */
    public Ejecutar.TRSIMULACTRNI.TRSIMULACEVTY.ACVTIPOCOBROV createEjecutarTRSIMULACTRNITRSIMULACEVTYACVTIPOCOBROV() {
        return new Ejecutar.TRSIMULACTRNI.TRSIMULACEVTY.ACVTIPOCOBROV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRSIMULACTRNI.TRSIMULACEVTY.ACVLIMCONCEDIDOV }
     * 
     */
    public Ejecutar.TRSIMULACTRNI.TRSIMULACEVTY.ACVLIMCONCEDIDOV createEjecutarTRSIMULACTRNITRSIMULACEVTYACVLIMCONCEDIDOV() {
        return new Ejecutar.TRSIMULACTRNI.TRSIMULACEVTY.ACVLIMCONCEDIDOV();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EjecutarResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_SIMUL_AC_TRN", name = "EjecutarResult")
    public JAXBElement<EjecutarResult> createEjecutarResult(EjecutarResult value) {
        return new JAXBElement<EjecutarResult>(_EjecutarResult_QNAME, EjecutarResult.class, null, value);
    }

}
