package mx.babel.bansefi.banksystem.response.mensajes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2015-05-20T15:33:40.753-05:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = "http://10.200.14.110:3095/WebServices/NSABCMSG", name = "SoapPort")
@XmlSeeAlso({ObjectFactory.class})
public interface SoapPort {

    @WebResult(name = "EjecutarResult", targetNamespace = "http://10.200.14.110:3095/WebServices/NSABCMSG")
    @RequestWrapper(localName = "Ejecutar", targetNamespace = "http://10.200.14.110:3095/WebServices/NSABCMSG", className = "mx.babel.bansefi.banksystem.base.webservices.mensajes.Ejecutar")
    @WebMethod(operationName = "Ejecutar", action = "http://10.200.14.110:3095/WebServices/NSABCMSG/Ejecutar")
    @ResponseWrapper(localName = "EjecutarResponse", targetNamespace = "http://10.200.14.110:3095/WebServices/NSABCMSG", className = "mx.babel.bansefi.banksystem.base.webservices.mensajes.EjecutarResponse")
    public mx.babel.bansefi.banksystem.response.mensajes.EjecutarResult ejecutar(
        @WebParam(name = "USERHEADER", targetNamespace = "http://10.200.14.110:3095/WebServices/NSABCMSG")
        java.lang.String userheader,
        @WebParam(name = "PASSHEADER", targetNamespace = "http://10.200.14.110:3095/WebServices/NSABCMSG")
        java.lang.String passheader,
        @WebParam(name = "IPHEADER", targetNamespace = "http://10.200.14.110:3095/WebServices/NSABCMSG")
        java.lang.String ipheader,
        @WebParam(name = "OPCION", targetNamespace = "http://10.200.14.110:3095/WebServices/NSABCMSG")
        java.lang.String opcion,
        @WebParam(name = "ENTIDAD", targetNamespace = "http://10.200.14.110:3095/WebServices/NSABCMSG")
        java.lang.String entidad,
        @WebParam(name = "REGION", targetNamespace = "http://10.200.14.110:3095/WebServices/NSABCMSG")
        java.lang.String region,
        @WebParam(name = "CENTRO", targetNamespace = "http://10.200.14.110:3095/WebServices/NSABCMSG")
        java.lang.String centro,
        @WebParam(name = "USUARIO", targetNamespace = "http://10.200.14.110:3095/WebServices/NSABCMSG")
        java.lang.String usuario,
        @WebParam(name = "CLAVE", targetNamespace = "http://10.200.14.110:3095/WebServices/NSABCMSG")
        java.math.BigInteger clave,
        @WebParam(name = "TERMINAL", targetNamespace = "http://10.200.14.110:3095/WebServices/NSABCMSG")
        java.lang.String terminal,
        @WebParam(name = "PRIORIDAD", targetNamespace = "http://10.200.14.110:3095/WebServices/NSABCMSG")
        java.math.BigInteger prioridad,
        @WebParam(name = "TEXTO", targetNamespace = "http://10.200.14.110:3095/WebServices/NSABCMSG")
        java.lang.String texto,
        @WebParam(name = "FEC_VIG_DESDE", targetNamespace = "http://10.200.14.110:3095/WebServices/NSABCMSG")
        java.lang.String fecVIGDESDE,
        @WebParam(name = "FEC_VIG_HASTA", targetNamespace = "http://10.200.14.110:3095/WebServices/NSABCMSG")
        java.lang.String fecVIGHASTA
    );
}