package mx.babel.bansefi.banksystem.response.consultadomicilio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2015-03-30T19:07:36.371-06:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_CONS_DOMIC_PPAL_TRN", name = "SoapPort")
@XmlSeeAlso({ObjectFactory.class})
public interface SoapPort {

    @WebResult(name = "EjecutarResult", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_CONS_DOMIC_PPAL_TRN")
    @RequestWrapper(localName = "Ejecutar", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_CONS_DOMIC_PPAL_TRN", className = "mx.babel.bansefi.banksystem.personas.webservices.consultadomicilio.Ejecutar")
    @WebMethod(operationName = "Ejecutar", action = "http://10.200.14.110:3300/WebServicesNSS/TR_CONS_DOMIC_PPAL_TRN/Ejecutar")
    @ResponseWrapper(localName = "EjecutarResponse", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_CONS_DOMIC_PPAL_TRN", className = "mx.babel.bansefi.banksystem.personas.webservices.consultadomicilio.EjecutarResponse")
    public mx.babel.bansefi.banksystem.response.consultadomicilio.EjecutarResult ejecutar(
        @WebParam(name = "TR_CONS_DOMIC_PPAL_TRN_I", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_CONS_DOMIC_PPAL_TRN")
        mx.babel.bansefi.banksystem.response.consultadomicilio.Ejecutar.TRCONSDOMICPPALTRNI trCONSDOMICPPALTRNI
    );
}
