package mx.babel.bansefi.banksystem.base.webservices.consultaautorizaciones;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2015-06-13T11:50:21.119-05:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_CONSULTA_GLOBAL_AT_TRN", name = "SoapPort")
@XmlSeeAlso({ObjectFactory.class})
public interface SoapPort {

    @WebResult(name = "EjecutarResult", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_CONSULTA_GLOBAL_AT_TRN")
    @RequestWrapper(localName = "Ejecutar", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_CONSULTA_GLOBAL_AT_TRN", className = "mx.babel.bansefi.banksystem.base.webservices.consultaautorizaciones.Ejecutar")
    @WebMethod(operationName = "Ejecutar", action = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_CONSULTA_GLOBAL_AT_TRN/Ejecutar")
    @ResponseWrapper(localName = "EjecutarResponse", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_CONSULTA_GLOBAL_AT_TRN", className = "mx.babel.bansefi.banksystem.base.webservices.consultaautorizaciones.EjecutarResponse")
    public mx.babel.bansefi.banksystem.base.webservices.consultaautorizaciones.EjecutarResult ejecutar(
        @WebParam(name = "USERHEADER", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_CONSULTA_GLOBAL_AT_TRN")
        java.lang.String userheader,
        @WebParam(name = "PASSHEADER", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_CONSULTA_GLOBAL_AT_TRN")
        java.lang.String passheader,
        @WebParam(name = "IPHEADER", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_CONSULTA_GLOBAL_AT_TRN")
        java.lang.String ipheader,
        @WebParam(name = "ITR_CONSULTA_GLOBAL_AT_TR", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_CONSULTA_GLOBAL_AT_TRN")
        mx.babel.bansefi.banksystem.base.webservices.consultaautorizaciones.Ejecutar.ITRCONSULTAGLOBALATTR itrCONSULTAGLOBALATTR
    );
}
