package mx.babel.bansefi.banksystem.base.webservices.busquedaanotaciones;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.babel.arq.comun.constants.ServicioWebConstants;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2015-06-03T16:33:21.271-05:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_AN_CONS_ANOT_M_TRN", name = "SoapPort")
@XmlSeeAlso({ObjectFactory.class})
public interface SoapPort {

    @WebResult(name = "EjecutarResult", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_AN_CONS_ANOT_M_TRN")
    @RequestWrapper(localName = "Ejecutar", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_AN_CONS_ANOT_M_TRN", className = "bansefinss.webservicesnss.tr_an_cons_anot_m_trn.Ejecutar")
    @WebMethod(operationName = "Ejecutar", action = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_AN_CONS_ANOT_M_TRN/Ejecutar")
    @ResponseWrapper(localName = "EjecutarResponse", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_AN_CONS_ANOT_M_TRN", className = "bansefinss.webservicesnss.tr_an_cons_anot_m_trn.EjecutarResponse")
    public mx.babel.bansefi.banksystem.base.webservices.busquedaanotaciones.EjecutarResult ejecutar(
        @WebParam(name = "TR_AN_CONS_ANOT_M_TRN_I", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_AN_CONS_ANOT_M_TRN")
        mx.babel.bansefi.banksystem.base.webservices.busquedaanotaciones.Ejecutar.TRANCONSANOTMTRNI trANCONSANOTMTRNI
    );
}
