package mx.babel.bansefi.banksystem.cuentas.webservices.consultacondicionrango;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import mx.babel.arq.comun.constants.ServicioWebConstants;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2015-06-16T11:37:41.614-05:00
 * Generated source version: 2.7.7.redhat-1
 *
 */
@WebServiceClient(name = "TR_CONS_VAL_KA_RNG_TRN",
                  wsdlLocation = "",
                  targetNamespace = "")
public class ConsultaCondicionRangoServicio extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName(ServicioWebConstants.TARGETNAMESPACE_TRN + "TR_CONS_VAL_KA_RNG_TRN", "TR_CONS_VAL_KA_RNG_TRN");
    public final static QName SOAPPORT = new QName(ServicioWebConstants.TARGETNAMESPACE_TRN + "TR_CONS_VAL_KA_RNG_TRN", "SoapPort");
    static {
        URL url = null;
        try {
            url = new URL(ServicioWebConstants.URL_WSDL+"TR_CONS_VAL_KA_RNG_TRN/WSDL");
        } catch (final MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConsultaCondicionRangoServicio.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", ServicioWebConstants.URL_WSDL+"TR_CONS_VAL_KA_RNG_TRN/WSDL");
        }
        WSDL_LOCATION = url;
    }

    public ConsultaCondicionRangoServicio(final URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsultaCondicionRangoServicio(final URL wsdlLocation, final QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaCondicionRangoServicio() {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConsultaCondicionRangoServicio(final WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConsultaCondicionRangoServicio(final URL wsdlLocation, final WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConsultaCondicionRangoServicio(final URL wsdlLocation, final QName serviceName, final WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SoapPort
     */
    @WebEndpoint(name = "SoapPort")
    public SoapPort getSoapPort() {
        return super.getPort(SOAPPORT, SoapPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapPort
     */
    @WebEndpoint(name = "SoapPort")
    public SoapPort getSoapPort(final WebServiceFeature... features) {
        return super.getPort(SOAPPORT, SoapPort.class, features);
    }

}
