package mx.babel.bansefi.banksystem.response.consultaretenciones;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2015-04-20T17:57:25.604-05:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_CONSULTA_GLOBAL_RT_TRN", name = "SoapPort")
@XmlSeeAlso({ObjectFactory.class})
public interface SoapPort {

    @WebResult(name = "EjecutarResult", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_CONSULTA_GLOBAL_RT_TRN")
    @RequestWrapper(localName = "Ejecutar", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_CONSULTA_GLOBAL_RT_TRN", className = "mx.babel.bansefi.banksystem.wwwww.Ejecutar")
    @WebMethod(operationName = "Ejecutar", action = "http://10.200.14.110:3300/WebServicesNSS/TR_CONSULTA_GLOBAL_RT_TRN/Ejecutar")
    @ResponseWrapper(localName = "EjecutarResponse", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_CONSULTA_GLOBAL_RT_TRN", className = "mx.babel.bansefi.banksystem.wwwww.EjecutarResponse")
    public mx.babel.bansefi.banksystem.response.consultaretenciones.EjecutarResult ejecutar(
        @WebParam(name = "TR_CONSULTA_GLOBAL_RT_TRN_I", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_CONSULTA_GLOBAL_RT_TRN")
        mx.babel.bansefi.banksystem.response.consultaretenciones.Ejecutar.TRCONSULTAGLOBALRTTRNI trCONSULTAGLOBALRTTRNI
    );
}
