
package mx.babel.bansefi.banksystem.base.webservices.consultaproductossimplesporcuenta;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the mx.babel.bansefi.banksystem.base.webservices.consultaproductossimplesporcuenta package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EJECUTARRESULT_QNAME = new QName(mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_PRESENTACION_AC_TRN", "EjecutarResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.babel.bansefi.banksystem.base.webservices.consultaproductossimplesporcuenta
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ejecutar }
     *
     */
    public Ejecutar createEjecutar() {
        return new Ejecutar();
    }

    /**
     * Create an instance of {@link ResponseBansefi }
     *
     */
    public ResponseBansefi createResponseBansefi() {
        return new ResponseBansefi();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO createResponseBansefiOTRPRESENTACIONACTRNO() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZ() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZTRCONSVALMSVKPEVTZ() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZTRCONSVALMSVKPEVTZKACDAC1V() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPRESENTACIONACTRNI }
     *
     */
    public Ejecutar.ITRPRESENTACIONACTRNI createEjecutarITRPRESENTACIONACTRNI() {
        return new Ejecutar.ITRPRESENTACIONACTRNI();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPRESENTACIONACTRNI.TRPRESENTACIONACEVTY }
     *
     */
    public Ejecutar.ITRPRESENTACIONACTRNI.TRPRESENTACIONACEVTY createEjecutarITRPRESENTACIONACTRNITRPRESENTACIONACEVTY() {
        return new Ejecutar.ITRPRESENTACIONACTRNI.TRPRESENTACIONACEVTY();
    }

    /**
     * Create an instance of {@link EjecutarResponse }
     *
     */
    public EjecutarResponse createEjecutarResponse() {
        return new EjecutarResponse();
    }

    /**
     * Create an instance of {@link EjecutarResult }
     *
     */
    public EjecutarResult createEjecutarResult() {
        return new EjecutarResult();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.STDTRNMSJPARMV }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.STDTRNMSJPARMV createResponseBansefiOTRPRESENTACIONACTRNOSTDTRNMSJPARMV() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.STDTRNMSJPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.STDTRNOPARMV }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.STDTRNOPARMV createResponseBansefiOTRPRESENTACIONACTRNOSTDTRNOPARMV() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.STDTRNOPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.ACPDSLD }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.ACPDSLD createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZACPDSLD() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.ACPDSLD();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.PERSONAACV }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.PERSONAACV createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZPERSONAACV() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.PERSONAACV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.CODNUMRCOMONEDAV }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.CODNUMRCOMONEDAV createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZCODNUMRCOMONEDAV() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.CODNUMRCOMONEDAV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KACDACE }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KACDACE createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZTRCONSVALMSVKPEVTZKACDAC1VKACDACE() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KACDACE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAESTRCTVLISTAV }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAESTRCTVLISTAV createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZTRCONSVALMSVKPEVTZKACDAC1VKAESTRCTVLISTAV() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAESTRCTVLISTAV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAKARLPKDOMV }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAKARLPKDOMV createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZTRCONSVALMSVKPEVTZKACDAC1VKAKARLPKDOMV() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAKARLPKDOMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAESTRCTRNGV }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAESTRCTRNGV createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZTRCONSVALMSVKPEVTZKACDAC1VKAESTRCTRNGV() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAESTRCTRNGV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAESTRCTVRNGV }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAESTRCTVRNGV createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZTRCONSVALMSVKPEVTZKACDAC1VKAESTRCTVRNGV() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAESTRCTVRNGV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAESTRCTCMSN1V }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAESTRCTCMSN1V createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZTRCONSVALMSVKPEVTZKACDAC1VKAESTRCTCMSN1V() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAESTRCTCMSN1V();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KACMSNPRCTLV }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KACMSNPRCTLV createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZTRCONSVALMSVKPEVTZKACDAC1VKACMSNPRCTLV() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KACMSNPRCTLV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KACMSNFIJV }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KACMSNFIJV createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZTRCONSVALMSVKPEVTZKACDAC1VKACMSNFIJV() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KACMSNFIJV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAESTRCTINT1V }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAESTRCTINT1V createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZTRCONSVALMSVKPEVTZKACDAC1VKAESTRCTINT1V() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAESTRCTINT1V();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAESTRCTINTFIJV }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAESTRCTINTFIJV createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZTRCONSVALMSVKPEVTZKACDAC1VKAESTRCTINTFIJV() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAESTRCTINTFIJV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAESTRCTINTVARV }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAESTRCTINTVARV createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZTRCONSVALMSVKPEVTZKACDAC1VKAESTRCTINTVARV() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAESTRCTINTVARV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAINTFRANQ1V }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAINTFRANQ1V createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZTRCONSVALMSVKPEVTZKACDAC1VKAINTFRANQ1V() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAINTFRANQ1V();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAINTFRANQFIJV }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAINTFRANQFIJV createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZTRCONSVALMSVKPEVTZKACDAC1VKAINTFRANQFIJV() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAINTFRANQFIJV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAINTFRANQVARV }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAINTFRANQVARV createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZTRCONSVALMSVKPEVTZKACDAC1VKAINTFRANQVARV() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAINTFRANQVARV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAINTRLSPV }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAINTRLSPV createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZTRCONSVALMSVKPEVTZKACDAC1VKAINTRLSPV() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAINTRLSPV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAMATRIZV }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAMATRIZV createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZTRCONSVALMSVKPEVTZKACDAC1VKAMATRIZV() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.KAMATRIZV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.IDCCPS1V }
     *
     */
    public ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.IDCCPS1V createResponseBansefiOTRPRESENTACIONACTRNOTRPRESENTACIONACEVTZTRCONSVALMSVKPEVTZKACDAC1VIDCCPS1V() {
        return new ResponseBansefi.OTRPRESENTACIONACTRNO.TRPRESENTACIONACEVTZ.TRCONSVALMSVKPEVTZ.KACDAC1V.IDCCPS1V();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPRESENTACIONACTRNI.STDTRNIPARMV }
     *
     */
    public Ejecutar.ITRPRESENTACIONACTRNI.STDTRNIPARMV createEjecutarITRPRESENTACIONACTRNISTDTRNIPARMV() {
        return new Ejecutar.ITRPRESENTACIONACTRNI.STDTRNIPARMV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPRESENTACIONACTRNI.TRPRESENTACIONACEVTY.ACPDSLD }
     *
     */
    public Ejecutar.ITRPRESENTACIONACTRNI.TRPRESENTACIONACEVTY.ACPDSLD createEjecutarITRPRESENTACIONACTRNITRPRESENTACIONACEVTYACPDSLD() {
        return new Ejecutar.ITRPRESENTACIONACTRNI.TRPRESENTACIONACEVTY.ACPDSLD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPRESENTACIONACTRNI.TRPRESENTACIONACEVTY.ACDATOSV }
     *
     */
    public Ejecutar.ITRPRESENTACIONACTRNI.TRPRESENTACIONACEVTY.ACDATOSV createEjecutarITRPRESENTACIONACTRNITRPRESENTACIONACEVTYACDATOSV() {
        return new Ejecutar.ITRPRESENTACIONACTRNI.TRPRESENTACIONACEVTY.ACDATOSV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPRESENTACIONACTRNI.TRPRESENTACIONACEVTY.ACACP }
     *
     */
    public Ejecutar.ITRPRESENTACIONACTRNI.TRPRESENTACIONACEVTY.ACACP createEjecutarITRPRESENTACIONACTRNITRPRESENTACIONACEVTYACACP() {
        return new Ejecutar.ITRPRESENTACIONACTRNI.TRPRESENTACIONACEVTY.ACACP();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPRESENTACIONACTRNI.TRPRESENTACIONACEVTY.KAREPOSV }
     *
     */
    public Ejecutar.ITRPRESENTACIONACTRNI.TRPRESENTACIONACEVTY.KAREPOSV createEjecutarITRPRESENTACIONACTRNITRPRESENTACIONACEVTYKAREPOSV() {
        return new Ejecutar.ITRPRESENTACIONACTRNI.TRPRESENTACIONACEVTY.KAREPOSV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPRESENTACIONACTRNI.TRPRESENTACIONACEVTY.FECHAVALORV }
     *
     */
    public Ejecutar.ITRPRESENTACIONACTRNI.TRPRESENTACIONACEVTY.FECHAVALORV createEjecutarITRPRESENTACIONACTRNITRPRESENTACIONACEVTYFECHAVALORV() {
        return new Ejecutar.ITRPRESENTACIONACTRNI.TRPRESENTACIONACEVTY.FECHAVALORV();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EjecutarResult }{@code >}}
     *
     */
    @XmlElementDecl(namespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_PRESENTACION_AC_TRN", name = "EjecutarResult")
    public JAXBElement<EjecutarResult> createEjecutarResult(final EjecutarResult value) {
        return new JAXBElement<EjecutarResult>(_EJECUTARRESULT_QNAME, EjecutarResult.class, null, value);
    }

}
