package mx.babel.bansefi.banksystem.response.busquedaidexterna;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2015-03-30T17:11:52.184-06:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_PE_CB_ID_EXTERNA_CNS_TRN", name = "SoapPort")
@XmlSeeAlso({ObjectFactory.class})
public interface SoapPort {

    @WebResult(name = "EjecutarResult", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_PE_CB_ID_EXTERNA_CNS_TRN")
    @RequestWrapper(localName = "Ejecutar", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_PE_CB_ID_EXTERNA_CNS_TRN", className = "bansefinss.webservicesnss.tr_pe_cb_id_externa_cns_trn.Ejecutar")
    @WebMethod(operationName = "Ejecutar", action = "http://BansefiNSS/WebServicesNSS/TR_PE_CB_ID_EXTERNA_CNS_TRN/Ejecutar")
    @ResponseWrapper(localName = "EjecutarResponse", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_PE_CB_ID_EXTERNA_CNS_TRN", className = "bansefinss.webservicesnss.tr_pe_cb_id_externa_cns_trn.EjecutarResponse")
    public mx.babel.bansefi.banksystem.response.busquedaidexterna.EjecutarResult ejecutar(
        @WebParam(name = "TR_PE_CB_ID_EXTERNA_CNS_TRN_I", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_PE_CB_ID_EXTERNA_CNS_TRN")
        mx.babel.bansefi.banksystem.response.busquedaidexterna.Ejecutar.TRPECBIDEXTERNACNSTRNI trPECBIDEXTERNACNSTRNI
    );
}
