package mx.babel.bansefi.banksystem.administracion.webservices.modificacionatribuciones;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2015-07-25T17:12:03.702-05:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_EP_MODIF_ATRIB_EMPL_TRN", name = "SoapPort")
@XmlSeeAlso({ObjectFactory.class})
public interface SoapPort {

    @WebResult(name = "EjecutarResult", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_EP_MODIF_ATRIB_EMPL_TRN")
    @RequestWrapper(localName = "Ejecutar", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_EP_MODIF_ATRIB_EMPL_TRN", className = "bansefinss.webservicesnss.tr_ep_modif_atrib_empl_trn.Ejecutar")
    @WebMethod(operationName = "Ejecutar", action = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_EP_MODIF_ATRIB_EMPL_TRN/Ejecutar")
    @ResponseWrapper(localName = "EjecutarResponse", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_EP_MODIF_ATRIB_EMPL_TRN", className = "bansefinss.webservicesnss.tr_ep_modif_atrib_empl_trn.EjecutarResponse")
    public mx.babel.bansefi.banksystem.administracion.webservices.modificacionatribuciones.EjecutarResult ejecutar(
        @WebParam(name = "USERHEADER", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_EP_MODIF_ATRIB_EMPL_TRN")
        java.lang.String userheader,
        @WebParam(name = "PASSHEADER", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_EP_MODIF_ATRIB_EMPL_TRN")
        java.lang.String passheader,
        @WebParam(name = "IPHEADER", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_EP_MODIF_ATRIB_EMPL_TRN")
        java.lang.String ipheader,
        @WebParam(name = "ITR_EP_MODIF_ATRIB_EMPL_T", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_EP_MODIF_ATRIB_EMPL_TRN")
        mx.babel.bansefi.banksystem.administracion.webservices.modificacionatribuciones.Ejecutar.ITREPMODIFATRIBEMPLT itrEPMODIFATRIBEMPLT
    );
}
