
package mx.babel.bansefi.banksystem.personas.webservices.modificacionpersonafisica;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.babel.bansefi.banksystem.personas.webservices.modificacionpersonafisica package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName EJECUTAR_RESULT_QNAME = new QName(mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_PE_MODIF_INDV_TRN", "EjecutarResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.babel.bansefi.banksystem.personas.webservices.modificacionpersonafisica
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ejecutar }
     * 
     */
    public Ejecutar createEjecutar() {
        return new Ejecutar();
    }

    /**
     * Create an instance of {@link ResponseBansefi }
     * 
     */
    public ResponseBansefi createResponseBansefi() {
        return new ResponseBansefi();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPEMODIFINDVTRNO }
     * 
     */
    public ResponseBansefi.OTRPEMODIFINDVTRNO createResponseBansefiOTRPEMODIFINDVTRNO() {
        return new ResponseBansefi.OTRPEMODIFINDVTRNO();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPEMODIFINDVTRNO.TRPEMODIFINDVEVTZ }
     * 
     */
    public ResponseBansefi.OTRPEMODIFINDVTRNO.TRPEMODIFINDVEVTZ createResponseBansefiOTRPEMODIFINDVTRNOTRPEMODIFINDVEVTZ() {
        return new ResponseBansefi.OTRPEMODIFINDVTRNO.TRPEMODIFINDVEVTZ();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI createEjecutarITRPEMODIFINDVTRNI() {
        return new Ejecutar.ITRPEMODIFINDVTRNI();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTY() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVV() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.PECOMPARTIRDOMICOBJTRDV }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.PECOMPARTIRDOMICOBJTRDV createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYPECOMPARTIRDOMICOBJTRDV() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.PECOMPARTIRDOMICOBJTRDV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.DRDMDPOBJTRDV }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.DRDMDPOBJTRDV createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYDRDMDPOBJTRDV() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.DRDMDPOBJTRDV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.PEALTAINDVOBJTRDV }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.PEALTAINDVOBJTRDV createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYPEALTAINDVOBJTRDV() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.PEALTAINDVOBJTRDV();
    }

    /**
     * Create an instance of {@link EjecutarResponse }
     * 
     */
    public EjecutarResponse createEjecutarResponse() {
        return new EjecutarResponse();
    }

    /**
     * Create an instance of {@link EjecutarResult }
     * 
     */
    public EjecutarResult createEjecutarResult() {
        return new EjecutarResult();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPEMODIFINDVTRNO.STDTRNMSJPARMV }
     * 
     */
    public ResponseBansefi.OTRPEMODIFINDVTRNO.STDTRNMSJPARMV createResponseBansefiOTRPEMODIFINDVTRNOSTDTRNMSJPARMV() {
        return new ResponseBansefi.OTRPEMODIFINDVTRNO.STDTRNMSJPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPEMODIFINDVTRNO.STDTRNOPARMV }
     * 
     */
    public ResponseBansefi.OTRPEMODIFINDVTRNO.STDTRNOPARMV createResponseBansefiOTRPEMODIFINDVTRNOSTDTRNOPARMV() {
        return new ResponseBansefi.OTRPEMODIFINDVTRNO.STDTRNOPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPEMODIFINDVTRNO.TRPEMODIFINDVEVTZ.PERIDENNOMBGRV }
     * 
     */
    public ResponseBansefi.OTRPEMODIFINDVTRNO.TRPEMODIFINDVEVTZ.PERIDENNOMBGRV createResponseBansefiOTRPEMODIFINDVTRNOTRPEMODIFINDVEVTZPERIDENNOMBGRV() {
        return new ResponseBansefi.OTRPEMODIFINDVTRNO.TRPEMODIFINDVEVTZ.PERIDENNOMBGRV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPEMODIFINDVTRNO.TRPEMODIFINDVEVTZ.DRDOMICP }
     * 
     */
    public ResponseBansefi.OTRPEMODIFINDVTRNO.TRPEMODIFINDVEVTZ.DRDOMICP createResponseBansefiOTRPEMODIFINDVTRNOTRPEMODIFINDVEVTZDRDOMICP() {
        return new ResponseBansefi.OTRPEMODIFINDVTRNO.TRPEMODIFINDVEVTZ.DRDOMICP();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPEMODIFINDVTRNO.TRPEMODIFINDVEVTZ.PEPERSP }
     * 
     */
    public ResponseBansefi.OTRPEMODIFINDVTRNO.TRPEMODIFINDVEVTZ.PEPERSP createResponseBansefiOTRPEMODIFINDVTRNOTRPEMODIFINDVEVTZPEPERSP() {
        return new ResponseBansefi.OTRPEMODIFINDVTRNO.TRPEMODIFINDVEVTZ.PEPERSP();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.STDTRNIPARMV }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.STDTRNIPARMV createEjecutarITRPEMODIFINDVTRNISTDTRNIPARMV() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.STDTRNIPARMV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.AGLOCALIDADNOCODV }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.AGLOCALIDADNOCODV createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYAGLOCALIDADNOCODV() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.AGLOCALIDADNOCODV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMASDIRV }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMASDIRV createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMASDIRV() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMASDIRV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDAVISOFALLEC }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDAVISOFALLEC createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDAVISOFALLEC() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDAVISOFALLEC();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDAVISONONIF }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDAVISONONIF createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDAVISONONIF() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDAVISONONIF();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDAVISOSITECO }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDAVISOSITECO createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDAVISOSITECO() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDAVISOSITECO();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDAVISOREPRES }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDAVISOREPRES createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDAVISOREPRES() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDAVISOREPRES();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDAVISOTARJRES }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDAVISOTARJRES createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDAVISOTARJRES() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDAVISOTARJRES();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDPLNFCNPETICNIFV }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDPLNFCNPETICNIFV createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDPLNFCNPETICNIFV() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDPLNFCNPETICNIFV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDPLNFCNDESBLOQV }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDPLNFCNDESBLOQV createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDPLNFCNDESBLOQV() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDPLNFCNDESBLOQV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.PEPERSINDCLIENTEV }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.PEPERSINDCLIENTEV createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYPEPERSINDCLIENTEV() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.PEPERSINDCLIENTEV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.PECOMPARTIRDOMICV }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.PECOMPARTIRDOMICV createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYPECOMPARTIRDOMICV() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.PECOMPARTIRDOMICV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEPERSUPD }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEPERSUPD createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDPEPERSUPD() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEPERSUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEINDVUPD }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEINDVUPD createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDPEINDVUPD() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEINDVUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEIDEXTUPD }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEIDEXTUPD createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDPEIDEXTUPD() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEIDEXTUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEIDEXTUPDDEL }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEIDEXTUPDDEL createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDPEIDEXTUPDDEL() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEIDEXTUPDDEL();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEIDEXTINS }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEIDEXTINS createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDPEIDEXTINS() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEIDEXTINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEACTPROFINDVINS }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEACTPROFINDVINS createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDPEACTPROFINDVINS() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEACTPROFINDVINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEOTROCNAEUPD }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEOTROCNAEUPD createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDPEOTROCNAEUPD() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEOTROCNAEUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEOTROCNAEINS }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEOTROCNAEINS createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDPEOTROCNAEINS() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEOTROCNAEINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPD }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPD createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDPECPCDADLGLINDVUPD() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPDDEL }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPDDEL createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDPECPCDADLGLINDVUPDDEL() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPDDEL();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVINS }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVINS createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDPECPCDADLGLINDVINS() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPESITECONUPD }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPESITECONUPD createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDPESITECONUPD() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPESITECONUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPESITECONINS }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPESITECONINS createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDPESITECONINS() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPESITECONINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOUPD }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOUPD createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDPEPERSRLARGEOUPD() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOINS }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOINS createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDPEPERSRLARGEOINS() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDAGLOCALIDADNOCODINS }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDAGLOCALIDADNOCODINS createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDAGLOCALIDADNOCODINS() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDAGLOCALIDADNOCODINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEINDVFRDLNTAUPD }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEINDVFRDLNTAUPD createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDPEINDVFRDLNTAUPD() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDPEINDVFRDLNTAUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDCLCLIENTINS }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDCLCLIENTINS createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDCLCLIENTINS() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDCLCLIENTINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDDRDOMICCOMPARTIR }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDDRDOMICCOMPARTIR createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDDRDOMICCOMPARTIR() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDDRDOMICCOMPARTIR();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDDRDOMICUPD }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDDRDOMICUPD createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDDRDOMICUPD() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDDRDOMICUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDDRDOMICINS }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDDRDOMICINS createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDDRDOMICINS() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDDRDOMICINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDDRDOMICUPDCOMPARTIR }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDDRDOMICUPDCOMPARTIR createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDDRDOMICUPDCOMPARTIR() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDDRDOMICUPDCOMPARTIR();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDSOLOMODIDOMIC }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDSOLOMODIDOMIC createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDSOLOMODIDOMIC() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDSOLOMODIDOMIC();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDMODINUMDIRPRAL }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDMODINUMDIRPRAL createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYINDMODIFCLINDVVINDMODINUMDIRPRAL() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.INDMODIFCLINDVV.INDMODINUMDIRPRAL();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.PECOMPARTIRDOMICOBJTRDV.CODPERSRLDIRV }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.PECOMPARTIRDOMICOBJTRDV.CODPERSRLDIRV createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYPECOMPARTIRDOMICOBJTRDVCODPERSRLDIRV() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.PECOMPARTIRDOMICOBJTRDV.CODPERSRLDIRV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.DRDMDPOBJTRDV.CODPERSRLDIRV }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.DRDMDPOBJTRDV.CODPERSRLDIRV createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYDRDMDPOBJTRDVCODPERSRLDIRV() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.DRDMDPOBJTRDV.CODPERSRLDIRV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.DRDMDPOBJTRDV.CODARGEODOMICILIOV }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.DRDMDPOBJTRDV.CODARGEODOMICILIOV createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYDRDMDPOBJTRDVCODARGEODOMICILIOV() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.DRDMDPOBJTRDV.CODARGEODOMICILIOV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.DRDMDPOBJTRDV.NUMARGEODOMICILIOV }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.DRDMDPOBJTRDV.NUMARGEODOMICILIOV createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYDRDMDPOBJTRDVNUMARGEODOMICILIOV() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.DRDMDPOBJTRDV.NUMARGEODOMICILIOV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.DRDMDPOBJTRDV.COMPDOMICV }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.DRDMDPOBJTRDV.COMPDOMICV createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYDRDMDPOBJTRDVCOMPDOMICV() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.DRDMDPOBJTRDV.COMPDOMICV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.DRDMDPOBJTRDV.DRELCTRV }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.DRDMDPOBJTRDV.DRELCTRV createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYDRDMDPOBJTRDVDRELCTRV() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.DRDMDPOBJTRDV.DRELCTRV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.PEALTAINDVOBJTRDV.PERLARGEONUMV }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.PEALTAINDVOBJTRDV.PERLARGEONUMV createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYPEALTAINDVOBJTRDVPERLARGEONUMV() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.PEALTAINDVOBJTRDV.PERLARGEONUMV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.PEALTAINDVOBJTRDV.AGLOCNOCODNUMV }
     * 
     */
    public Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.PEALTAINDVOBJTRDV.AGLOCNOCODNUMV createEjecutarITRPEMODIFINDVTRNITRPEMODIFINDVEVTYPEALTAINDVOBJTRDVAGLOCNOCODNUMV() {
        return new Ejecutar.ITRPEMODIFINDVTRNI.TRPEMODIFINDVEVTY.PEALTAINDVOBJTRDV.AGLOCNOCODNUMV();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EjecutarResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_PE_MODIF_INDV_TRN", name = "EjecutarResult")
    public JAXBElement<EjecutarResult> createEjecutarResult(EjecutarResult value) {
        return new JAXBElement<EjecutarResult>(EJECUTAR_RESULT_QNAME, EjecutarResult.class, null, value);
    }

}
