
package mx.babel.bansefi.banksystem.administracion.webservices.modificacionempleado;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.babel.bansefi.banksystem.administracion.webservices.modificacionempleado package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName EJECUTAR_RESULT_QNAME = new QName(mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_MODIF_EMPL_TRN", "EjecutarResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.babel.bansefi.banksystem.administracion.webservices.modificacionempleado
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ejecutar }
     * 
     */
    public Ejecutar createEjecutar() {
        return new Ejecutar();
    }

    /**
     * Create an instance of {@link ResponseBansefi }
     * 
     */
    public ResponseBansefi createResponseBansefi() {
        return new ResponseBansefi();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRMODIFEMPLTRNO }
     * 
     */
    public ResponseBansefi.OTRMODIFEMPLTRNO createResponseBansefiOTRMODIFEMPLTRNO() {
        return new ResponseBansefi.OTRMODIFEMPLTRNO();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRMODIFEMPLTRNO.TRMODIFEMPLEVTZ }
     * 
     */
    public ResponseBansefi.OTRMODIFEMPLTRNO.TRMODIFEMPLEVTZ createResponseBansefiOTRMODIFEMPLTRNOTRMODIFEMPLEVTZ() {
        return new ResponseBansefi.OTRMODIFEMPLTRNO.TRMODIFEMPLEVTZ();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI createEjecutarITRMODIFEMPLTRNI() {
        return new Ejecutar.ITRMODIFEMPLTRNI();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTY() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PECOMPARTIRDOMICOBJTRDV }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PECOMPARTIRDOMICOBJTRDV createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYPECOMPARTIRDOMICOBJTRDV() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PECOMPARTIRDOMICOBJTRDV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYDRDMDPOBJTRDV() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEALTAINDVOBJTRDV }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEALTAINDVOBJTRDV createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYPEALTAINDVOBJTRDV() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEALTAINDVOBJTRDV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFEPEMPLV() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVV() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV();
    }

    /**
     * Create an instance of {@link EjecutarResponse }
     * 
     */
    public EjecutarResponse createEjecutarResponse() {
        return new EjecutarResponse();
    }

    /**
     * Create an instance of {@link EjecutarResult }
     * 
     */
    public EjecutarResult createEjecutarResult() {
        return new EjecutarResult();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRMODIFEMPLTRNO.STDTRNMSJPARMV }
     * 
     */
    public ResponseBansefi.OTRMODIFEMPLTRNO.STDTRNMSJPARMV createResponseBansefiOTRMODIFEMPLTRNOSTDTRNMSJPARMV() {
        return new ResponseBansefi.OTRMODIFEMPLTRNO.STDTRNMSJPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRMODIFEMPLTRNO.STDTRNOPARMV }
     * 
     */
    public ResponseBansefi.OTRMODIFEMPLTRNO.STDTRNOPARMV createResponseBansefiOTRMODIFEMPLTRNOSTDTRNOPARMV() {
        return new ResponseBansefi.OTRMODIFEMPLTRNO.STDTRNOPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.PERIDENNOMBGRV }
     * 
     */
    public ResponseBansefi.OTRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.PERIDENNOMBGRV createResponseBansefiOTRMODIFEMPLTRNOTRMODIFEMPLEVTZPERIDENNOMBGRV() {
        return new ResponseBansefi.OTRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.PERIDENNOMBGRV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.DRDOMICP }
     * 
     */
    public ResponseBansefi.OTRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.DRDOMICP createResponseBansefiOTRMODIFEMPLTRNOTRMODIFEMPLEVTZDRDOMICP() {
        return new ResponseBansefi.OTRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.DRDOMICP();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.PEPERSP }
     * 
     */
    public ResponseBansefi.OTRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.PEPERSP createResponseBansefiOTRMODIFEMPLTRNOTRMODIFEMPLEVTZPEPERSP() {
        return new ResponseBansefi.OTRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.PEPERSP();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.CLAVEEMPLEADOV }
     * 
     */
    public ResponseBansefi.OTRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.CLAVEEMPLEADOV createResponseBansefiOTRMODIFEMPLTRNOTRMODIFEMPLEVTZCLAVEEMPLEADOV() {
        return new ResponseBansefi.OTRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.CLAVEEMPLEADOV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.STDTRNIPARMV }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.STDTRNIPARMV createEjecutarITRMODIFEMPLTRNISTDTRNIPARMV() {
        return new Ejecutar.ITRMODIFEMPLTRNI.STDTRNIPARMV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.EPPEDPOBJTRDV }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.EPPEDPOBJTRDV createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYEPPEDPOBJTRDV() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.EPPEDPOBJTRDV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.EPEMPLP }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.EPEMPLP createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYEPEMPLP() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.EPEMPLP();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.AGLOCALIDADNOCODV }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.AGLOCALIDADNOCODV createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYAGLOCALIDADNOCODV() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.AGLOCALIDADNOCODV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMASDIRV }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMASDIRV createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMASDIRV() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMASDIRV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEPERSINDCLIENTEV }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEPERSINDCLIENTEV createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYPEPERSINDCLIENTEV() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEPERSINDCLIENTEV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDAVISOFALLEC }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDAVISOFALLEC createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDAVISOFALLEC() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDAVISOFALLEC();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDAVISOSITECO }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDAVISOSITECO createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDAVISOSITECO() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDAVISOSITECO();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDAVISOTARJRES }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDAVISOTARJRES createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDAVISOTARJRES() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDAVISOTARJRES();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PECOMPARTIRDOMICV }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PECOMPARTIRDOMICV createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYPECOMPARTIRDOMICV() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PECOMPARTIRDOMICV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PECOMPARTIRDOMICOBJTRDV.CODPERSRLDIRV }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PECOMPARTIRDOMICOBJTRDV.CODPERSRLDIRV createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYPECOMPARTIRDOMICOBJTRDVCODPERSRLDIRV() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PECOMPARTIRDOMICOBJTRDV.CODPERSRLDIRV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.CODPERSRLDIRV }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.CODPERSRLDIRV createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYDRDMDPOBJTRDVCODPERSRLDIRV() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.CODPERSRLDIRV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.CODARGEODOMICILIOV }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.CODARGEODOMICILIOV createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYDRDMDPOBJTRDVCODARGEODOMICILIOV() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.CODARGEODOMICILIOV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.NUMARGEODOMICILIOV }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.NUMARGEODOMICILIOV createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYDRDMDPOBJTRDVNUMARGEODOMICILIOV() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.NUMARGEODOMICILIOV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.COMPDOMICV }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.COMPDOMICV createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYDRDMDPOBJTRDVCOMPDOMICV() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.COMPDOMICV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.DRELCTRV }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.DRELCTRV createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYDRDMDPOBJTRDVDRELCTRV() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.DRELCTRV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEALTAINDVOBJTRDV.PERLARGEONUMV }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEALTAINDVOBJTRDV.PERLARGEONUMV createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYPEALTAINDVOBJTRDVPERLARGEONUMV() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEALTAINDVOBJTRDV.PERLARGEONUMV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEALTAINDVOBJTRDV.AGLOCNOCODNUMV }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEALTAINDVOBJTRDV.AGLOCNOCODNUMV createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYPEALTAINDVOBJTRDVAGLOCNOCODNUMV() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEALTAINDVOBJTRDV.AGLOCNOCODNUMV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPEMPLINS }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPEMPLINS createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFEPEMPLVINDEPEMPLINS() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPEMPLINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPEMPLUPD }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPEMPLUPD createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFEPEMPLVINDEPEMPLUPD() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPEMPLUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPCARGOEMPLUPD }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPCARGOEMPLUPD createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFEPEMPLVINDEPCARGOEMPLUPD() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPCARGOEMPLUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPEMPLRLCENTUPD }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPEMPLRLCENTUPD createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFEPEMPLVINDEPEMPLRLCENTUPD() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPEMPLRLCENTUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEPERSUPD }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEPERSUPD createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPEPERSUPD() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEPERSUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEINDVUPD }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEINDVUPD createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPEINDVUPD() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEINDVUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEIDEXTUPD }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEIDEXTUPD createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPEIDEXTUPD() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEIDEXTUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEIDEXTUPDDEL }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEIDEXTUPDDEL createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPEIDEXTUPDDEL() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEIDEXTUPDDEL();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEIDEXTINS }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEIDEXTINS createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPEIDEXTINS() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEIDEXTINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEACTPROFINDVINS }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEACTPROFINDVINS createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPEACTPROFINDVINS() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEACTPROFINDVINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEOTROCNAEUPD }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEOTROCNAEUPD createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPEOTROCNAEUPD() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEOTROCNAEUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEOTROCNAEINS }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEOTROCNAEINS createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPEOTROCNAEINS() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEOTROCNAEINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPD }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPD createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPECPCDADLGLINDVUPD() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPDDEL }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPDDEL createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPECPCDADLGLINDVUPDDEL() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPDDEL();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVINS }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVINS createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPECPCDADLGLINDVINS() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPESITECONUPD }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPESITECONUPD createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPESITECONUPD() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPESITECONUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPESITECONINS }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPESITECONINS createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPESITECONINS() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPESITECONINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOUPD }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOUPD createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPEPERSRLARGEOUPD() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOINS }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOINS createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPEPERSRLARGEOINS() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDAGLOCALIDADNOCODINS }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDAGLOCALIDADNOCODINS createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDAGLOCALIDADNOCODINS() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDAGLOCALIDADNOCODINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEINDVFRDLNTAUPD }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEINDVFRDLNTAUPD createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPEINDVFRDLNTAUPD() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEINDVFRDLNTAUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDCLCLIENTINS }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDCLCLIENTINS createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDCLCLIENTINS() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDCLCLIENTINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICCOMPARTIR }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICCOMPARTIR createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDDRDOMICCOMPARTIR() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICCOMPARTIR();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICUPD }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICUPD createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDDRDOMICUPD() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICINS }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICINS createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDDRDOMICINS() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICUPDCOMPARTIR }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICUPDCOMPARTIR createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDDRDOMICUPDCOMPARTIR() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICUPDCOMPARTIR();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDSOLOMODIDOMIC }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDSOLOMODIDOMIC createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDSOLOMODIDOMIC() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDSOLOMODIDOMIC();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDMODINUMDIRPRAL }
     * 
     */
    public Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDMODINUMDIRPRAL createEjecutarITRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDMODINUMDIRPRAL() {
        return new Ejecutar.ITRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDMODINUMDIRPRAL();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EjecutarResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_MODIF_EMPL_TRN", name = "EjecutarResult")
    public JAXBElement<EjecutarResult> createEjecutarResult(EjecutarResult value) {
        return new JAXBElement<EjecutarResult>(EJECUTAR_RESULT_QNAME, EjecutarResult.class, null, value);
    }

}
