package mx.babel.bansefi.banksystem.transacciones.webservices.anulacionrecibonodomiciliado;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.babel.arq.comun.constants.ServicioWebConstants;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2015-07-20T13:13:56.426-05:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_ANULACION_APLCCN_RV_TRN", name = "SoapPort")
@XmlSeeAlso({ObjectFactory.class})
public interface SoapPort {

    @WebResult(name = "EjecutarResult", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_ANULACION_APLCCN_RV_TRN")
    @RequestWrapper(localName = "Ejecutar", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_ANULACION_APLCCN_RV_TRN", className = "mx.babel.bansefi.banksystem.webservices.anulacionrecibonodomiciliado.Ejecutar")
    @WebMethod(operationName = "Ejecutar", action = ServicioWebConstants.URL_TRN + "TR_ANULACION_APLCCN_RV_TRN/Ejecutar")
    @ResponseWrapper(localName = "EjecutarResponse", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_ANULACION_APLCCN_RV_TRN", className = "mx.babel.bansefi.banksystem.webservices.anulacionrecibonodomiciliado.EjecutarResponse")
    public mx.babel.bansefi.banksystem.transacciones.webservices.anulacionrecibonodomiciliado.EjecutarResult ejecutar(
        @WebParam(name = "USERHEADER", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_ANULACION_APLCCN_RV_TRN")
        java.lang.String userheader,
        @WebParam(name = "PASSHEADER", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_ANULACION_APLCCN_RV_TRN")
        java.lang.String passheader,
        @WebParam(name = "IPHEADER", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_ANULACION_APLCCN_RV_TRN")
        java.lang.String ipheader,
        @WebParam(name = "ITR_ANULACION_APLCCN_RV_T", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_ANULACION_APLCCN_RV_TRN")
        mx.babel.bansefi.banksystem.transacciones.webservices.anulacionrecibonodomiciliado.Ejecutar.ITRANULACIONAPLCCNRVT itrANULACIONAPLCCNRVT
    );
}
