package mx.babel.bansefi.banksystem.cuentas.webservices.registrogasto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2016-02-23T10:54:23.247-06:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebService(targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_ALTA_GASTOS_EXT_TRN", name = "SoapPort")
@XmlSeeAlso({ObjectFactory.class})
public interface SoapPort {

    @WebResult(name = "EjecutarResult", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_ALTA_GASTOS_EXT_TRN")
    @RequestWrapper(localName = "Ejecutar", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_ALTA_GASTOS_EXT_TRN", className = "mx.babel.bansefi.banksystem.cuentas.webservices.registrogasto.Ejecutar")
    @WebMethod(operationName = "Ejecutar", action = "http://BansefiNSS/WebServicesNSS/TR_ALTA_GASTOS_EXT_TRN/Ejecutar")
    @ResponseWrapper(localName = "EjecutarResponse", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_ALTA_GASTOS_EXT_TRN", className = "mx.babel.bansefi.banksystem.cuentas.webservices.registrogasto.EjecutarResponse")
    public mx.babel.bansefi.banksystem.cuentas.webservices.registrogasto.EjecutarResult ejecutar(
        @WebParam(name = "USERHEADER", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_ALTA_GASTOS_EXT_TRN")
        java.lang.String userheader,
        @WebParam(name = "PASSHEADER", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_ALTA_GASTOS_EXT_TRN")
        java.lang.String passheader,
        @WebParam(name = "IPHEADER", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_ALTA_GASTOS_EXT_TRN")
        java.lang.String ipheader,
        @WebParam(name = "ITR_ALTA_GASTOS_EXT_TRN_I", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_ALTA_GASTOS_EXT_TRN")
        mx.babel.bansefi.banksystem.cuentas.webservices.registrogasto.Ejecutar.ITRALTAGASTOSEXTTRNI itrALTAGASTOSEXTTRNI
    );
}
