package mx.babel.bansefi.banksystem.response.consultaempleado;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2015-04-16T17:56:39.271-05:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_CONS_EMPL_TRN", name = "SoapPort")
@XmlSeeAlso({ObjectFactory.class})
public interface SoapPort {

    @WebResult(name = "EjecutarResult", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_CONS_EMPL_TRN")
    @RequestWrapper(localName = "Ejecutar", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_CONS_EMPL_TRN", className = "bansefinss.webservicesnss.tr_cons_empl_trn.Ejecutar")
    @WebMethod(operationName = "Ejecutar", action = "http://10.200.14.110:3300/WebServicesNSS/TR_CONS_EMPL_TRN/Ejecutar")
    @ResponseWrapper(localName = "EjecutarResponse", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_CONS_EMPL_TRN", className = "bansefinss.webservicesnss.tr_cons_empl_trn.EjecutarResponse")
    public mx.babel.bansefi.banksystem.response.consultaempleado.EjecutarResult ejecutar(
        @WebParam(name = "TR_CONS_EMPL_TRN_I", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_CONS_EMPL_TRN")
        mx.babel.bansefi.banksystem.response.consultaempleado.Ejecutar.TRCONSEMPLTRNI trCONSEMPLTRNI
    );
}
