package mx.babel.bansefi.banksystem.contabilidad.webservices.altaapuntemanualcaja;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2015-09-07T12:16:38.029-05:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "T1_AM_INI_APNTE_MANO_TRN", name = "SoapPort")
@XmlSeeAlso({ObjectFactory.class})
public interface SoapPort {

    @WebResult(name = "EjecutarResult", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "T1_AM_INI_APNTE_MANO_TRN")
    @RequestWrapper(localName = "Ejecutar", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "T1_AM_INI_APNTE_MANO_TRN", className = "mx.babel.bansefi.banksystem.contabilidad.webservices.altaApunteManual.Ejecutar")
    @WebMethod(operationName = "Ejecutar", action = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "T1_AM_INI_APNTE_MANO_TRN/Ejecutar")
    @ResponseWrapper(localName = "EjecutarResponse", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "T1_AM_INI_APNTE_MANO_TRN", className = "mx.babel.bansefi.banksystem.contabilidad.webservices.altaApunteManual.EjecutarResponse")
    public mx.babel.bansefi.banksystem.contabilidad.webservices.altaapuntemanualcaja.EjecutarResult ejecutar(
        @WebParam(name = "USERHEADER", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "T1_AM_INI_APNTE_MANO_TRN")
        java.lang.String userheader,
        @WebParam(name = "PASSHEADER", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "T1_AM_INI_APNTE_MANO_TRN")
        java.lang.String passheader,
        @WebParam(name = "IPHEADER", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "T1_AM_INI_APNTE_MANO_TRN")
        java.lang.String ipheader,
        @WebParam(name = "ITR_AM_INI_APNTE_MANO_TRN", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "T1_AM_INI_APNTE_MANO_TRN")
        mx.babel.bansefi.banksystem.contabilidad.webservices.altaapuntemanualcaja.Ejecutar.ITRAMINIAPNTEMANOTRN itrAMINIAPNTEMANOTRN
    );
}
