
package mx.babel.bansefi.banksystem.base.webservices.modificacionpersonamoral;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.babel.bansefi.banksystem.personas.webservices.modificacionpersonamoral package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName EJECUTAR_RESULT_QNAME = new QName(mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_PE_MODIF_ORG_TRN", "EjecutarResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.babel.bansefi.banksystem.personas.webservices.modificacionpersonamoral
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ejecutar }
     * 
     */
    public Ejecutar createEjecutar() {
        return new Ejecutar();
    }

    /**
     * Create an instance of {@link ResponseBansefi }
     * 
     */
    public ResponseBansefi createResponseBansefi() {
        return new ResponseBansefi();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPEMODIFORGTRNO }
     * 
     */
    public ResponseBansefi.OTRPEMODIFORGTRNO createResponseBansefiOTRPEMODIFORGTRNO() {
        return new ResponseBansefi.OTRPEMODIFORGTRNO();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPEMODIFORGTRNO.TRPEMODIFORGEVTZ }
     * 
     */
    public ResponseBansefi.OTRPEMODIFORGTRNO.TRPEMODIFORGEVTZ createResponseBansefiOTRPEMODIFORGTRNOTRPEMODIFORGEVTZ() {
        return new ResponseBansefi.OTRPEMODIFORGTRNO.TRPEMODIFORGEVTZ();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI createEjecutarITRPEMODIFORGTRNI() {
        return new Ejecutar.ITRPEMODIFORGTRNI();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTY() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLORGV }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLORGV createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLORGV() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLORGV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVV() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PECOMPARTIRDOMICOBJTRDV }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PECOMPARTIRDOMICOBJTRDV createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYPECOMPARTIRDOMICOBJTRDV() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PECOMPARTIRDOMICOBJTRDV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.DRDMDPOBJTRDV }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.DRDMDPOBJTRDV createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYDRDMDPOBJTRDV() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.DRDMDPOBJTRDV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PEALTAORGOBJTRDV }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PEALTAORGOBJTRDV createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYPEALTAORGOBJTRDV() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PEALTAORGOBJTRDV();
    }

    /**
     * Create an instance of {@link EjecutarResponse }
     * 
     */
    public EjecutarResponse createEjecutarResponse() {
        return new EjecutarResponse();
    }

    /**
     * Create an instance of {@link EjecutarResult }
     * 
     */
    public EjecutarResult createEjecutarResult() {
        return new EjecutarResult();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPEMODIFORGTRNO.STDTRNMSJPARMV }
     * 
     */
    public ResponseBansefi.OTRPEMODIFORGTRNO.STDTRNMSJPARMV createResponseBansefiOTRPEMODIFORGTRNOSTDTRNMSJPARMV() {
        return new ResponseBansefi.OTRPEMODIFORGTRNO.STDTRNMSJPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPEMODIFORGTRNO.STDTRNOPARMV }
     * 
     */
    public ResponseBansefi.OTRPEMODIFORGTRNO.STDTRNOPARMV createResponseBansefiOTRPEMODIFORGTRNOSTDTRNOPARMV() {
        return new ResponseBansefi.OTRPEMODIFORGTRNO.STDTRNOPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPEMODIFORGTRNO.TRPEMODIFORGEVTZ.PERIDENNOMBGRV }
     * 
     */
    public ResponseBansefi.OTRPEMODIFORGTRNO.TRPEMODIFORGEVTZ.PERIDENNOMBGRV createResponseBansefiOTRPEMODIFORGTRNOTRPEMODIFORGEVTZPERIDENNOMBGRV() {
        return new ResponseBansefi.OTRPEMODIFORGTRNO.TRPEMODIFORGEVTZ.PERIDENNOMBGRV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPEMODIFORGTRNO.TRPEMODIFORGEVTZ.DRDOMICP }
     * 
     */
    public ResponseBansefi.OTRPEMODIFORGTRNO.TRPEMODIFORGEVTZ.DRDOMICP createResponseBansefiOTRPEMODIFORGTRNOTRPEMODIFORGEVTZDRDOMICP() {
        return new ResponseBansefi.OTRPEMODIFORGTRNO.TRPEMODIFORGEVTZ.DRDOMICP();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRPEMODIFORGTRNO.TRPEMODIFORGEVTZ.PEPERSP }
     * 
     */
    public ResponseBansefi.OTRPEMODIFORGTRNO.TRPEMODIFORGEVTZ.PEPERSP createResponseBansefiOTRPEMODIFORGTRNOTRPEMODIFORGEVTZPEPERSP() {
        return new ResponseBansefi.OTRPEMODIFORGTRNO.TRPEMODIFORGEVTZ.PEPERSP();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.STDTRNIPARMV }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.STDTRNIPARMV createEjecutarITRPEMODIFORGTRNISTDTRNIPARMV() {
        return new Ejecutar.ITRPEMODIFORGTRNI.STDTRNIPARMV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.AGLOCALIDADNOCODV }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.AGLOCALIDADNOCODV createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYAGLOCALIDADNOCODV() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.AGLOCALIDADNOCODV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMASDIRV }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMASDIRV createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMASDIRV() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMASDIRV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PEPERSINDCLIENTEV }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PEPERSINDCLIENTEV createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYPEPERSINDCLIENTEV() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PEPERSINDCLIENTEV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDAVISOFALLEC }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDAVISOFALLEC createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDAVISOFALLEC() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDAVISOFALLEC();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDAVISONONIF }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDAVISONONIF createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDAVISONONIF() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDAVISONONIF();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDAVISOSITECO }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDAVISOSITECO createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDAVISOSITECO() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDAVISOSITECO();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDPLNFCNDESBLOQV }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDPLNFCNDESBLOQV createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDPLNFCNDESBLOQV() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDPLNFCNDESBLOQV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PECOMPARTIRDOMICV }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PECOMPARTIRDOMICV createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYPECOMPARTIRDOMICV() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PECOMPARTIRDOMICV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLORGV.INDPEORGUPD }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLORGV.INDPEORGUPD createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLORGVINDPEORGUPD() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLORGV.INDPEORGUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLORGV.INDPEORGFRDLNTAUPD }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLORGV.INDPEORGFRDLNTAUPD createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLORGVINDPEORGFRDLNTAUPD() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLORGV.INDPEORGFRDLNTAUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLORGV.INDDRRGSTROINS }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLORGV.INDDRRGSTROINS createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLORGVINDDRRGSTROINS() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLORGV.INDDRRGSTROINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLORGV.INDDRRGSTROUPD }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLORGV.INDDRRGSTROUPD createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLORGVINDDRRGSTROUPD() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLORGV.INDDRRGSTROUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEPERSUPD }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEPERSUPD createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDPEPERSUPD() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEPERSUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEINDVUPD }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEINDVUPD createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDPEINDVUPD() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEINDVUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEIDEXTUPD }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEIDEXTUPD createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDPEIDEXTUPD() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEIDEXTUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEIDEXTUPDDEL }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEIDEXTUPDDEL createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDPEIDEXTUPDDEL() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEIDEXTUPDDEL();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEIDEXTINS }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEIDEXTINS createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDPEIDEXTINS() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEIDEXTINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEACTPROFINDVINS }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEACTPROFINDVINS createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDPEACTPROFINDVINS() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEACTPROFINDVINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEOTROCNAEUPD }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEOTROCNAEUPD createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDPEOTROCNAEUPD() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEOTROCNAEUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEOTROCNAEINS }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEOTROCNAEINS createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDPEOTROCNAEINS() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEOTROCNAEINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPD }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPD createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDPECPCDADLGLINDVUPD() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPDDEL }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPDDEL createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDPECPCDADLGLINDVUPDDEL() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPDDEL();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVINS }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVINS createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDPECPCDADLGLINDVINS() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPESITECONUPD }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPESITECONUPD createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDPESITECONUPD() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPESITECONUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPESITECONINS }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPESITECONINS createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDPESITECONINS() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPESITECONINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOUPD }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOUPD createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDPEPERSRLARGEOUPD() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOINS }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOINS createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDPEPERSRLARGEOINS() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDAGLOCALIDADNOCODINS }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDAGLOCALIDADNOCODINS createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDAGLOCALIDADNOCODINS() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDAGLOCALIDADNOCODINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEINDVFRDLNTAUPD }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEINDVFRDLNTAUPD createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDPEINDVFRDLNTAUPD() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDPEINDVFRDLNTAUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDCLCLIENTINS }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDCLCLIENTINS createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDCLCLIENTINS() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDCLCLIENTINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDDRDOMICCOMPARTIR }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDDRDOMICCOMPARTIR createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDDRDOMICCOMPARTIR() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDDRDOMICCOMPARTIR();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDDRDOMICUPD }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDDRDOMICUPD createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDDRDOMICUPD() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDDRDOMICUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDDRDOMICINS }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDDRDOMICINS createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDDRDOMICINS() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDDRDOMICINS();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDDRDOMICUPDCOMPARTIR }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDDRDOMICUPDCOMPARTIR createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDDRDOMICUPDCOMPARTIR() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDDRDOMICUPDCOMPARTIR();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDSOLOMODIDOMIC }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDSOLOMODIDOMIC createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDSOLOMODIDOMIC() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDSOLOMODIDOMIC();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDMODINUMDIRPRAL }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDMODINUMDIRPRAL createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYINDMODIFCLINDVVINDMODINUMDIRPRAL() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.INDMODIFCLINDVV.INDMODINUMDIRPRAL();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PECOMPARTIRDOMICOBJTRDV.CODPERSRLDIRV }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PECOMPARTIRDOMICOBJTRDV.CODPERSRLDIRV createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYPECOMPARTIRDOMICOBJTRDVCODPERSRLDIRV() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PECOMPARTIRDOMICOBJTRDV.CODPERSRLDIRV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.DRDMDPOBJTRDV.CODPERSRLDIRV }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.DRDMDPOBJTRDV.CODPERSRLDIRV createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYDRDMDPOBJTRDVCODPERSRLDIRV() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.DRDMDPOBJTRDV.CODPERSRLDIRV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.DRDMDPOBJTRDV.CODARGEODOMICILIOV }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.DRDMDPOBJTRDV.CODARGEODOMICILIOV createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYDRDMDPOBJTRDVCODARGEODOMICILIOV() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.DRDMDPOBJTRDV.CODARGEODOMICILIOV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.DRDMDPOBJTRDV.NUMARGEODOMICILIOV }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.DRDMDPOBJTRDV.NUMARGEODOMICILIOV createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYDRDMDPOBJTRDVNUMARGEODOMICILIOV() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.DRDMDPOBJTRDV.NUMARGEODOMICILIOV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.DRDMDPOBJTRDV.COMPDOMICV }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.DRDMDPOBJTRDV.COMPDOMICV createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYDRDMDPOBJTRDVCOMPDOMICV() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.DRDMDPOBJTRDV.COMPDOMICV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.DRDMDPOBJTRDV.DRELCTRV }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.DRDMDPOBJTRDV.DRELCTRV createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYDRDMDPOBJTRDVDRELCTRV() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.DRDMDPOBJTRDV.DRELCTRV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PEALTAORGOBJTRDV.PERLARGEONUMV }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PEALTAORGOBJTRDV.PERLARGEONUMV createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYPEALTAORGOBJTRDVPERLARGEONUMV() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PEALTAORGOBJTRDV.PERLARGEONUMV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PEALTAORGOBJTRDV.AGLOCNOCODNUMV }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PEALTAORGOBJTRDV.AGLOCNOCODNUMV createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYPEALTAORGOBJTRDVAGLOCNOCODNUMV() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PEALTAORGOBJTRDV.AGLOCNOCODNUMV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PEALTAORGOBJTRDV.DRREGNUMV }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PEALTAORGOBJTRDV.DRREGNUMV createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYPEALTAORGOBJTRDVDRREGNUMV() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PEALTAORGOBJTRDV.DRREGNUMV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PEALTAORGOBJTRDV.DRCOMPRGSTROV }
     * 
     */
    public Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PEALTAORGOBJTRDV.DRCOMPRGSTROV createEjecutarITRPEMODIFORGTRNITRPEMODIFORGEVTYPEALTAORGOBJTRDVDRCOMPRGSTROV() {
        return new Ejecutar.ITRPEMODIFORGTRNI.TRPEMODIFORGEVTY.PEALTAORGOBJTRDV.DRCOMPRGSTROV();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EjecutarResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_PE_MODIF_ORG_TRN", name = "EjecutarResult")
    public JAXBElement<EjecutarResult> createEjecutarResult(EjecutarResult value) {
        return new JAXBElement<EjecutarResult>(EJECUTAR_RESULT_QNAME, EjecutarResult.class, null, value);
    }

}
