package mx.babel.bansefi.banksystem.response.consultaintegrantesgrupo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2015-04-08T10:11:43.171-05:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_PE_CONSULTA_POSICION_TRN", name = "SoapPort")
@XmlSeeAlso({ObjectFactory.class})
public interface SoapPort {

    @WebResult(name = "EjecutarResult", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_PE_CONSULTA_POSICION_TRN")
    @RequestWrapper(localName = "Ejecutar", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_PE_CONSULTA_POSICION_TRN", className = "mx.babel.bansefi.banksystem.personas.webservices.consultaintegrantesgrupo.Ejecutar")
    @WebMethod(operationName = "Ejecutar", action = "http://10.200.14.110:3300/WebServicesNSS/TR_PE_CONSULTA_POSICION_TRN/Ejecutar")
    @ResponseWrapper(localName = "EjecutarResponse", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_PE_CONSULTA_POSICION_TRN", className = "mx.babel.bansefi.banksystem.personas.webservices.consultaintegrantesgrupo.EjecutarResponse")
    public mx.babel.bansefi.banksystem.response.consultaintegrantesgrupo.EjecutarResult ejecutar(
        @WebParam(name = "TR_PE_CONSULTA_POSICION_TRN_I", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_PE_CONSULTA_POSICION_TRN")
        mx.babel.bansefi.banksystem.response.consultaintegrantesgrupo.Ejecutar.TRPECONSULTAPOSICIONTRNI trPECONSULTAPOSICIONTRNI
    );
}
