
package mx.babel.bansefi.banksystem.cuentas.webservices.activacionplazo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.babel.bansefi.banksystem.cuentas.webservices.activacionplazo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName EJECUTARRESULT_QNAME = new QName(mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_ACTVCN_IMPSCN_PAG_TRN", "EjecutarResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.babel.bansefi.banksystem.cuentas.webservices.activacionplazo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ejecutar }
     * 
     */
    public Ejecutar createEjecutar() {
        return new Ejecutar();
    }

    /**
     * Create an instance of {@link ResponseBansefi }
     * 
     */
    public ResponseBansefi createResponseBansefi() {
        return new ResponseBansefi();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN createResponseBansefiOTRACTVCNIMPSCNPAGTRN() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.STDAUTORIZAV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.STDAUTORIZAV createResponseBansefiOTRACTVCNIMPSCNPAGTRNSTDAUTORIZAV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.STDAUTORIZAV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRLBACTUALIZALBEVTZ() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLINEASV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLINEASV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRLBACTUALIZALBEVTZLBDATOSLINEASV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLINEASV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLINEASV.IPFRECLIQIPV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLINEASV.IPFRECLIQIPV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRLBACTUALIZALBEVTZLBDATOSLINEASVIPFRECLIQIPV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLINEASV.IPFRECLIQIPV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSCARATULAV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSCARATULAV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRLBACTUALIZALBEVTZLBDATOSCARATULAV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSCARATULAV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVT() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTIPFSANNICOLASIMPRV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.NUMEROCUOTASV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.NUMEROCUOTASV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTNUMEROCUOTASV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.NUMEROCUOTASV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTIPDATOSIMPRESV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV.IPFRECLIQIPV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV.IPFRECLIQIPV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTIPDATOSIMPRESVIPFRECLIQIPV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV.IPFRECLIQIPV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRACTVCNIMPSCNPAGTRN }
     * 
     */
    public Ejecutar.ITRACTVCNIMPSCNPAGTRN createEjecutarITRACTVCNIMPSCNPAGTRN() {
        return new Ejecutar.ITRACTVCNIMPSCNPAGTRN();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRLBVALIDARLBEVTY }
     * 
     */
    public Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRLBVALIDARLBEVTY createEjecutarITRACTVCNIMPSCNPAGTRNTRLBVALIDARLBEVTY() {
        return new Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRLBVALIDARLBEVTY();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT }
     * 
     */
    public Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT createEjecutarITRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVT() {
        return new Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.CONDCUOTAV }
     * 
     */
    public Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.CONDCUOTAV createEjecutarITRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTCONDCUOTAV() {
        return new Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.CONDCUOTAV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRACTVCNIMPSCNPAGTRN.STDAUTORIZAV }
     * 
     */
    public Ejecutar.ITRACTVCNIMPSCNPAGTRN.STDAUTORIZAV createEjecutarITRACTVCNIMPSCNPAGTRNSTDAUTORIZAV() {
        return new Ejecutar.ITRACTVCNIMPSCNPAGTRN.STDAUTORIZAV();
    }

    /**
     * Create an instance of {@link EjecutarResponse }
     * 
     */
    public EjecutarResponse createEjecutarResponse() {
        return new EjecutarResponse();
    }

    /**
     * Create an instance of {@link EjecutarResult }
     * 
     */
    public EjecutarResult createEjecutarResult() {
        return new EjecutarResult();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.STDTRNMSJPARMV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.STDTRNMSJPARMV createResponseBansefiOTRACTVCNIMPSCNPAGTRNSTDTRNMSJPARMV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.STDTRNMSJPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.STDTRNOPARMV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.STDTRNOPARMV createResponseBansefiOTRACTVCNIMPSCNPAGTRNSTDTRNOPARMV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.STDTRNOPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.ARAUTREMOTAP }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.ARAUTREMOTAP createResponseBansefiOTRACTVCNIMPSCNPAGTRNSTDAUTORIZAVARAUTREMOTAP() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.ARAUTREMOTAP();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.ARTRNMSJPARMV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.ARTRNMSJPARMV createResponseBansefiOTRACTVCNIMPSCNPAGTRNSTDAUTORIZAVARTRNMSJPARMV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.ARTRNMSJPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.STDTARGETTERMINALV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.STDTARGETTERMINALV createResponseBansefiOTRACTVCNIMPSCNPAGTRNSTDAUTORIZAVSTDTARGETTERMINALV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.STDTARGETTERMINALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.ARIDSALTADOV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.ARIDSALTADOV createResponseBansefiOTRACTVCNIMPSCNPAGTRNSTDAUTORIZAVARIDSALTADOV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.ARIDSALTADOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.PSVACCIONREDENOMV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.PSVACCIONREDENOMV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRLBACTUALIZALBEVTZPSVACCIONREDENOMV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.PSVACCIONREDENOMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBNUMLINEASV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBNUMLINEASV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRLBACTUALIZALBEVTZLBNUMLINEASV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBNUMLINEASV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBMASDATOSV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBMASDATOSV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRLBACTUALIZALBEVTZLBMASDATOSV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBMASDATOSV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBNUEVALIBV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBNUEVALIBV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRLBACTUALIZALBEVTZLBNUEVALIBV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBNUEVALIBV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSACV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSACV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRLBACTUALIZALBEVTZLBDATOSACV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSACV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.NOMB50V }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.NOMB50V createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRLBACTUALIZALBEVTZNOMB50V() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.NOMB50V();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBSDOAPARV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBSDOAPARV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRLBACTUALIZALBEVTZLBSDOAPARV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBSDOAPARV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSTIPOLBV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSTIPOLBV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRLBACTUALIZALBEVTZLBDATOSTIPOLBV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSTIPOLBV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLBACTUALV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLBACTUALV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRLBACTUALIZALBEVTZLBDATOSLBACTUALV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLBACTUALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLBNUEVOSV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLBNUEVOSV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRLBACTUALIZALBEVTZLBDATOSLBNUEVOSV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLBNUEVOSV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLINEASV.PSVTXTINTLIBV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLINEASV.PSVTXTINTLIBV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRLBACTUALIZALBEVTZLBDATOSLINEASVPSVTXTINTLIBV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLINEASV.PSVTXTINTLIBV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLINEASV.IPDURACIPV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLINEASV.IPDURACIPV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRLBACTUALIZALBEVTZLBDATOSLINEASVIPDURACIPV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLINEASV.IPDURACIPV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLINEASV.LBINDLISTAIPESPV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLINEASV.LBINDLISTAIPESPV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRLBACTUALIZALBEVTZLBDATOSLINEASVLBINDLISTAIPESPV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLINEASV.LBINDLISTAIPESPV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLINEASV.IPFRECLIQIPV.IPINDLIQVTOV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLINEASV.IPFRECLIQIPV.IPINDLIQVTOV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRLBACTUALIZALBEVTZLBDATOSLINEASVIPFRECLIQIPVIPINDLIQVTOV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSLINEASV.IPFRECLIQIPV.IPINDLIQVTOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSCARATULAV.PSVCTAVIVIENDAV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSCARATULAV.PSVCTAVIVIENDAV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRLBACTUALIZALBEVTZLBDATOSCARATULAVPSVCTAVIVIENDAV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSCARATULAV.PSVCTAVIVIENDAV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSCARATULAV.PSVINDDISPOSIV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSCARATULAV.PSVINDDISPOSIV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRLBACTUALIZALBEVTZLBDATOSCARATULAVPSVINDDISPOSIV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSCARATULAV.PSVINDDISPOSIV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSCARATULAV.LBTITULARESV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSCARATULAV.LBTITULARESV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRLBACTUALIZALBEVTZLBDATOSCARATULAVLBTITULARESV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRLBACTUALIZALBEVTZ.LBDATOSCARATULAV.LBTITULARESV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.HLHCOLIQP }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.HLHCOLIQP createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTHLHCOLIQP() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.HLHCOLIQP();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.LIQIMPORTETOTALV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.LIQIMPORTETOTALV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTLIQIMPORTETOTALV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.LIQIMPORTETOTALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.LIQIMPSCNAPUNTESV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.LIQIMPSCNAPUNTESV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTLIQIMPSCNAPUNTESV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.LIQIMPSCNAPUNTESV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPIMPSCNV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPIMPSCNV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTIPIMPSCNV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPIMPSCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.PPLTIPOPRODUCTOV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.PPLTIPOPRODUCTOV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTPPLTIPOPRODUCTOV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.PPLTIPOPRODUCTOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.PPLCUENTAASOCIADAV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.PPLCUENTAASOCIADAV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTPPLCUENTAASOCIADAV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.PPLCUENTAASOCIADAV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.PSVCTAVIEJAV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.PSVCTAVIEJAV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTPSVCTAVIEJAV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.PSVCTAVIEJAV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.NOMBTRFAPDVV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.NOMBTRFAPDVV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTIPFSANNICOLASIMPRVNOMBTRFAPDVV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.NOMBTRFAPDVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.NOMBSUCURSALV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.NOMBSUCURSALV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTIPFSANNICOLASIMPRVNOMBSUCURSALV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.NOMBSUCURSALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.SALDOANTERIORV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.SALDOANTERIORV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTIPFSANNICOLASIMPRVSALDOANTERIORV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.SALDOANTERIORV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.SALDORESULTANTEV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.SALDORESULTANTEV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTIPFSANNICOLASIMPRVSALDORESULTANTEV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.SALDORESULTANTEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.SALDOOPERACIONV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.SALDOOPERACIONV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTIPFSANNICOLASIMPRVSALDOOPERACIONV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.SALDOOPERACIONV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.REINTERESMESV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.REINTERESMESV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTIPFSANNICOLASIMPRVREINTERESMESV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.REINTERESMESV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.REISRV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.REISRV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTIPFSANNICOLASIMPRVREISRV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.REISRV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.ACCARGOV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.ACCARGOV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTIPFSANNICOLASIMPRVACCARGOV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.ACCARGOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.NOMBEMPLEADOV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.NOMBEMPLEADOV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTIPFSANNICOLASIMPRVNOMBEMPLEADOV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.NOMBEMPLEADOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.NOMBRECLIENTEV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.NOMBRECLIENTEV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTIPFSANNICOLASIMPRVNOMBRECLIENTEV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPFSANNICOLASIMPRV.NOMBRECLIENTEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.NUMEROCUOTASV.CUOTASTOTV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.NUMEROCUOTASV.CUOTASTOTV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTNUMEROCUOTASVCUOTASTOTV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.NUMEROCUOTASV.CUOTASTOTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.NUMEROCUOTASV.CUOTASPAGADASV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.NUMEROCUOTASV.CUOTASPAGADASV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTNUMEROCUOTASVCUOTASPAGADASV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.NUMEROCUOTASV.CUOTASPAGADASV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV.IPINTERESV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV.IPINTERESV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTIPDATOSIMPRESVIPINTERESV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV.IPINTERESV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV.IPINTPRIMAV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV.IPINTPRIMAV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTIPDATOSIMPRESVIPINTPRIMAV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV.IPINTPRIMAV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV.IPDESCESPEV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV.IPDESCESPEV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTIPDATOSIMPRESVIPDESCESPEV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV.IPDESCESPEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV.IPFRANQUICIAV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV.IPFRANQUICIAV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTIPDATOSIMPRESVIPFRANQUICIAV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV.IPFRANQUICIAV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV.ACCARGOV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV.ACCARGOV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTIPDATOSIMPRESVACCARGOV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV.ACCARGOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV.IPFRECLIQIPV.IPINDLIQVTOV }
     * 
     */
    public ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV.IPFRECLIQIPV.IPINDLIQVTOV createResponseBansefiOTRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTIPDATOSIMPRESVIPFRECLIQIPVIPINDLIQVTOV() {
        return new ResponseBansefi.OTRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPDATOSIMPRESV.IPFRECLIQIPV.IPINDLIQVTOV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRACTVCNIMPSCNPAGTRN.STDTRNIPARMV }
     * 
     */
    public Ejecutar.ITRACTVCNIMPSCNPAGTRN.STDTRNIPARMV createEjecutarITRACTVCNIMPSCNPAGTRNSTDTRNIPARMV() {
        return new Ejecutar.ITRACTVCNIMPSCNPAGTRN.STDTRNIPARMV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRLBVALIDARLBEVTY.LBTIPOSELV }
     * 
     */
    public Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRLBVALIDARLBEVTY.LBTIPOSELV createEjecutarITRACTVCNIMPSCNPAGTRNTRLBVALIDARLBEVTYLBTIPOSELV() {
        return new Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRLBVALIDARLBEVTY.LBTIPOSELV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRLBVALIDARLBEVTY.LBLIBRETAP }
     * 
     */
    public Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRLBVALIDARLBEVTY.LBLIBRETAP createEjecutarITRACTVCNIMPSCNPAGTRNTRLBVALIDARLBEVTYLBLIBRETAP() {
        return new Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRLBVALIDARLBEVTY.LBLIBRETAP();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRLBVALIDARLBEVTY.IPOPCIONV }
     * 
     */
    public Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRLBVALIDARLBEVTY.IPOPCIONV createEjecutarITRACTVCNIMPSCNPAGTRNTRLBVALIDARLBEVTYIPOPCIONV() {
        return new Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRLBVALIDARLBEVTY.IPOPCIONV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPIMPSCNP }
     * 
     */
    public Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPIMPSCNP createEjecutarITRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTIPIMPSCNP() {
        return new Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.IPIMPSCNP();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.TRPETCNIMPSCNPAGEVTV }
     * 
     */
    public Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.TRPETCNIMPSCNPAGEVTV createEjecutarITRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTTRPETCNIMPSCNPAGEVTV() {
        return new Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.TRPETCNIMPSCNPAGEVTV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.PSVLIBRETAV }
     * 
     */
    public Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.PSVLIBRETAV createEjecutarITRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTPSVLIBRETAV() {
        return new Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.PSVLIBRETAV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.CONDCUOTAV.IPDATOSCONDV }
     * 
     */
    public Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.CONDCUOTAV.IPDATOSCONDV createEjecutarITRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTCONDCUOTAVIPDATOSCONDV() {
        return new Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.CONDCUOTAV.IPDATOSCONDV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.CONDCUOTAV.KSESTRCTVLISTAV }
     * 
     */
    public Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.CONDCUOTAV.KSESTRCTVLISTAV createEjecutarITRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTCONDCUOTAVKSESTRCTVLISTAV() {
        return new Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.CONDCUOTAV.KSESTRCTVLISTAV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.CONDCUOTAV.KSESTRCTVRNGV }
     * 
     */
    public Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.CONDCUOTAV.KSESTRCTVRNGV createEjecutarITRACTVCNIMPSCNPAGTRNTRACTVCNIMPSCNPAGEVTCONDCUOTAVKSESTRCTVRNGV() {
        return new Ejecutar.ITRACTVCNIMPSCNPAGTRN.TRACTVCNIMPSCNPAGEVT.CONDCUOTAV.KSESTRCTVRNGV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.ARAUTREMOTAP }
     * 
     */
    public Ejecutar.ITRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.ARAUTREMOTAP createEjecutarITRACTVCNIMPSCNPAGTRNSTDAUTORIZAVARAUTREMOTAP() {
        return new Ejecutar.ITRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.ARAUTREMOTAP();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.ARTRNMSJPARMV }
     * 
     */
    public Ejecutar.ITRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.ARTRNMSJPARMV createEjecutarITRACTVCNIMPSCNPAGTRNSTDAUTORIZAVARTRNMSJPARMV() {
        return new Ejecutar.ITRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.ARTRNMSJPARMV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.STDTARGETTERMINALV }
     * 
     */
    public Ejecutar.ITRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.STDTARGETTERMINALV createEjecutarITRACTVCNIMPSCNPAGTRNSTDAUTORIZAVSTDTARGETTERMINALV() {
        return new Ejecutar.ITRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.STDTARGETTERMINALV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.ARIDSALTADOV }
     * 
     */
    public Ejecutar.ITRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.ARIDSALTADOV createEjecutarITRACTVCNIMPSCNPAGTRNSTDAUTORIZAVARIDSALTADOV() {
        return new Ejecutar.ITRACTVCNIMPSCNPAGTRN.STDAUTORIZAV.ARIDSALTADOV();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EjecutarResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_ACTVCN_IMPSCN_PAG_TRN", name = "EjecutarResult")
    public JAXBElement<EjecutarResult> createEjecutarResult(EjecutarResult value) {
        return new JAXBElement<EjecutarResult>(EJECUTARRESULT_QNAME, EjecutarResult.class, null, value);
    }

}
