package mx.babel.bansefi.banksystem.response.consultasaldo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2015-04-28T10:48:04.732-05:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONSAL", name = "SoapPort")
@XmlSeeAlso({ObjectFactory.class})
public interface SoapPort {

    @WebResult(name = "EjecutarResult", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONSAL")
    @RequestWrapper(localName = "Ejecutar", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONSAL", className = "_110._14._200._10._3095.webservices.vtconsal.Ejecutar")
    @WebMethod(operationName = "Ejecutar", action = "http://10.200.14.110:3095/WebServices/VTCONSAL/Ejecutar")
    @ResponseWrapper(localName = "EjecutarResponse", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONSAL", className = "_110._14._200._10._3095.webservices.vtconsal.EjecutarResponse")
    public mx.babel.bansefi.banksystem.response.consultasaldo.EjecutarResult ejecutar(
        @WebParam(name = "USERHEADER", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONSAL")
        java.lang.String userheader,
        @WebParam(name = "PASSHEADER", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONSAL")
        java.lang.String passheader,
        @WebParam(name = "IPHEADER", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONSAL")
        java.lang.String ipheader,
        @WebParam(name = "ENTIDAD", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONSAL")
        java.lang.String entidad,
        @WebParam(name = "ACUERDO", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONSAL")
        java.math.BigInteger acuerdo,
        @WebParam(name = "CVEIDOF", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONSAL")
        java.lang.String cveidof,
        @WebParam(name = "NUMIFE", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONSAL")
        java.lang.String numife
    );
}
