
package mx.babel.bansefi.banksystem.cuentas.webservices.consultadatosdetalleipf;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the mx.babel.bansefi.banksystem.cuentas.webservices.consultadatosdetalleipf package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName EJECUTARRESULT_QNAME = new QName(mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_CONS_IMPSCN_INDIV_TRN", "EjecutarResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.babel.bansefi.banksystem.cuentas.webservices.consultadatosdetalleipf
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ejecutar }
     *
     */
    public Ejecutar createEjecutar() {
        return new Ejecutar();
    }

    /**
     * Create an instance of {@link ResponseBansefi }
     *
     */
    public ResponseBansefi createResponseBansefi() {
        return new ResponseBansefi();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN createResponseBansefiOTRCONSIMPSCNINDIVTRN() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT createResponseBansefiOTRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVT() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1 }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1 createResponseBansefiOTRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVTTRCONSIMPSCNINDIVEVT() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPFRECLIQIPV }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPFRECLIQIPV createResponseBansefiOTRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVTTRCONSIMPSCNINDIVEVTIPFRECLIQIPV() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPFRECLIQIPV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRCONSIMPSCNINDIVTRN }
     *
     */
    public Ejecutar.ITRCONSIMPSCNINDIVTRN createEjecutarITRCONSIMPSCNINDIVTRN() {
        return new Ejecutar.ITRCONSIMPSCNINDIVTRN();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT }
     *
     */
    public Ejecutar.ITRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT createEjecutarITRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVT() {
        return new Ejecutar.ITRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT();
    }

    /**
     * Create an instance of {@link EjecutarResponse }
     *
     */
    public EjecutarResponse createEjecutarResponse() {
        return new EjecutarResponse();
    }

    /**
     * Create an instance of {@link EjecutarResult }
     *
     */
    public EjecutarResult createEjecutarResult() {
        return new EjecutarResult();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.STDTRNMSJPARMV }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.STDTRNMSJPARMV createResponseBansefiOTRCONSIMPSCNINDIVTRNSTDTRNMSJPARMV() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.STDTRNMSJPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.STDTRNOPARMV }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.STDTRNOPARMV createResponseBansefiOTRCONSIMPSCNINDIVTRNSTDTRNOPARMV() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.STDTRNOPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.PSVCCCV }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.PSVCCCV createResponseBansefiOTRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVTPSVCCCV() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.PSVCCCV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.IPTITULARV }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.IPTITULARV createResponseBansefiOTRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVTIPTITULARV() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.IPTITULARV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.IPDATOSABONOIPV }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.IPDATOSABONOIPV createResponseBansefiOTRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVTIPDATOSABONOIPV() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.IPDATOSABONOIPV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPIMPNOMINALV }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPIMPNOMINALV createResponseBansefiOTRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVTTRCONSIMPSCNINDIVEVTIPIMPNOMINALV() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPIMPNOMINALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPFECHAVTOV }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPFECHAVTOV createResponseBansefiOTRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVTTRCONSIMPSCNINDIVEVTIPFECHAVTOV() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPFECHAVTOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPPROXLIQV }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPPROXLIQV createResponseBansefiOTRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVTTRCONSIMPSCNINDIVEVTIPPROXLIQV() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPPROXLIQV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPFULTLIQV }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPFULTLIQV createResponseBansefiOTRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVTTRCONSIMPSCNINDIVEVTIPFULTLIQV() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPFULTLIQV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPFECHACANCELACIONV }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPFECHACANCELACIONV createResponseBansefiOTRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVTTRCONSIMPSCNINDIVEVTIPFECHACANCELACIONV() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPFECHACANCELACIONV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPCAPITALIZABLEV }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPCAPITALIZABLEV createResponseBansefiOTRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVTTRCONSIMPSCNINDIVEVTIPCAPITALIZABLEV() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPCAPITALIZABLEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPRENOVABLEV }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPRENOVABLEV createResponseBansefiOTRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVTTRCONSIMPSCNINDIVEVTIPRENOVABLEV() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPRENOVABLEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPDURACIPV }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPDURACIPV createResponseBansefiOTRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVTTRCONSIMPSCNINDIVEVTIPDURACIPV() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPDURACIPV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPINTERESV }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPINTERESV createResponseBansefiOTRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVTTRCONSIMPSCNINDIVEVTIPINTERESV() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPINTERESV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPFRANQUICIAV }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPFRANQUICIAV createResponseBansefiOTRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVTTRCONSIMPSCNINDIVEVTIPFRANQUICIAV() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPFRANQUICIAV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPTAEV }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPTAEV createResponseBansefiOTRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVTTRCONSIMPSCNINDIVEVTIPTAEV() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPTAEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPINDESPECIESV }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPINDESPECIESV createResponseBansefiOTRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVTTRCONSIMPSCNINDIVEVTIPINDESPECIESV() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPINDESPECIESV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPDESCUENTOV }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPDESCUENTOV createResponseBansefiOTRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVTTRCONSIMPSCNINDIVEVTIPDESCUENTOV() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPDESCUENTOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPPRIMAVTOV }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPPRIMAVTOV createResponseBansefiOTRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVTTRCONSIMPSCNINDIVEVTIPPRIMAVTOV() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPPRIMAVTOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPFRECLIQIPV.IPINDLIQVTOV }
     *
     */
    public ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPFRECLIQIPV.IPINDLIQVTOV createResponseBansefiOTRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVTTRCONSIMPSCNINDIVEVTIPFRECLIQIPVIPINDLIQVTOV() {
        return new ResponseBansefi.OTRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.TRCONSIMPSCNINDIVEVT1.IPFRECLIQIPV.IPINDLIQVTOV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRCONSIMPSCNINDIVTRN.STDTRNIPARMV }
     *
     */
    public Ejecutar.ITRCONSIMPSCNINDIVTRN.STDTRNIPARMV createEjecutarITRCONSIMPSCNINDIVTRNSTDTRNIPARMV() {
        return new Ejecutar.ITRCONSIMPSCNINDIVTRN.STDTRNIPARMV();
    }

    /**
     * Create an instance of {@link Ejecutar.ITRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.IPIMPSCNP }
     *
     */
    public Ejecutar.ITRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.IPIMPSCNP createEjecutarITRCONSIMPSCNINDIVTRNTRCONSIMPSCNINDIVEVTIPIMPSCNP() {
        return new Ejecutar.ITRCONSIMPSCNINDIVTRN.TRCONSIMPSCNINDIVEVT.IPIMPSCNP();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EjecutarResult }{@code >}}
     *
     */
    @XmlElementDecl(namespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_CONS_IMPSCN_INDIV_TRN", name = "EjecutarResult")
    public JAXBElement<EjecutarResult> createEjecutarResult(final EjecutarResult value) {
        return new JAXBElement<EjecutarResult>(EJECUTARRESULT_QNAME, EjecutarResult.class, null, value);
    }

}
