package mx.babel.bansefi.banksystem.cajas.webservice.consultaparillabilletes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2015-10-23T10:32:27.943-05:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
//@WebService(targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_SOLIC_VF_SM_TRN", name = "SoapPort")
@WebService(targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_SOLIC_VF_SM_TRN", name = "SoapPort")
@XmlSeeAlso({ObjectFactory.class})
public interface SoapPort {

	@WebResult(name = "EjecutarResult", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_SOLIC_VF_SM_TRN")
    @RequestWrapper(localName = "Ejecutar", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_SOLIC_VF_SM_TRN", className = "mx.babel.bansefi.banksystem.cajas.webservice.consultaparillabilletes.Ejecutar")
  	@WebMethod(operationName = "Ejecutar", action = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_SOLIC_VF_SM_TRN/Ejecutar")
	@ResponseWrapper(localName = "EjecutarResponse", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_SOLIC_VF_SM_TRN", className = "mx.babel.bansefi.banksystem.cajas.webservice.consultaparillabilletes.EjecutarResponse")
    public mx.babel.bansefi.banksystem.cajas.webservice.consultaparillabilletes.EjecutarResult ejecutar(
        @WebParam(name = "USERHEADER", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_SOLIC_VF_SM_TRN")
        java.lang.String userheader,
        @WebParam(name = "PASSHEADER", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_SOLIC_VF_SM_TRN")
        java.lang.String passheader,
        @WebParam(name = "IPHEADER", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_SOLIC_VF_SM_TRN")
        java.lang.String ipheader,
        @WebParam(name = "ITR_SOLIC_VF_SM_TRN_I", targetNamespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_SOLIC_VF_SM_TRN")
        mx.babel.bansefi.banksystem.cajas.webservice.consultaparillabilletes.Ejecutar.ITRSOLICVFSMTRNI itrSOLICVFSMTRNI
    );
}
