package mx.babel.bansefi.banksystem.response.consultamovimientos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2015-04-28T10:53:52.103-05:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONMOV", name = "SoapPort")
@XmlSeeAlso({ObjectFactory.class})
public interface SoapPort {

    @WebResult(name = "EjecutarResult", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONMOV")
    @RequestWrapper(localName = "Ejecutar", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONMOV", className = "mx.babel.bansefi.banksystem.base.webservices.consultamovimientos.Ejecutar")
    @WebMethod(operationName = "Ejecutar", action = "http://10.200.14.110:3095/WebServices/VTCONMOV/Ejecutar")
    @ResponseWrapper(localName = "EjecutarResponse", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONMOV", className = "mx.babel.bansefi.banksystem.base.webservices.consultamovimientos.EjecutarResponse")
    public mx.babel.bansefi.banksystem.response.consultamovimientos.EjecutarResult ejecutar(
        @WebParam(name = "USERHEADER", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONMOV")
        java.lang.String userheader,
        @WebParam(name = "PASSHEADER", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONMOV")
        java.lang.String passheader,
        @WebParam(name = "IPHEADER", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONMOV")
        java.lang.String ipheader,
        @WebParam(name = "ENTIDAD", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONMOV")
        java.lang.String entidad,
        @WebParam(name = "ACUERDO", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONMOV")
        java.math.BigInteger acuerdo,
        @WebParam(name = "FECHA_DESDE", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONMOV")
        java.lang.String fechaDESDE,
        @WebParam(name = "FECHA_HASTA", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONMOV")
        java.lang.String fechaHASTA,
        @WebParam(name = "NUM_SEC", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONMOV")
        java.math.BigInteger numSEC,
        @WebParam(name = "CVEIDOF", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONMOV")
        java.lang.String cveidof,
        @WebParam(name = "NUM_IFE", targetNamespace = "http://10.200.14.110:3095/WebServices/VTCONMOV")
        java.lang.String numIFE
    );
}
