
package mx.babel.bansefi.banksystem.response.consultacuenta;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.babel.bansefi.banksystem.cuentas.webservices.consultacuenta package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EjecutarResult_QNAME = new QName("http://BansefiNSS/WebServicesNSS/TR_CONSULTA_ACUERDO_TRN", "EjecutarResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.babel.bansefi.banksystem.cuentas.webservices.consultacuenta
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ejecutar }
     * 
     */
    public Ejecutar createEjecutar() {
        return new Ejecutar();
    }

    /**
     * Create an instance of {@link ResponseBansefi }
     * 
     */
    public ResponseBansefi createResponseBansefi() {
        return new ResponseBansefi();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO createResponseBansefiTRCONSULTAACUERDOTRNO() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.STDANAVMSJV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.STDANAVMSJV createResponseBansefiTRCONSULTAACUERDOTRNOSTDANAVMSJV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.STDANAVMSJV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.STDANAVMSJV.STDANAVMSJLS }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.STDANAVMSJV.STDANAVMSJLS createResponseBansefiTRCONSULTAACUERDOTRNOSTDANAVMSJVSTDANAVMSJLS() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.STDANAVMSJV.STDANAVMSJLS();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZ() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZ() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1V() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSULTAACUERDOTRNI }
     * 
     */
    public Ejecutar.TRCONSULTAACUERDOTRNI createEjecutarTRCONSULTAACUERDOTRNI() {
        return new Ejecutar.TRCONSULTAACUERDOTRNI();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSULTAACUERDOTRNI.TRCONSULTAACUERDOEVTY }
     * 
     */
    public Ejecutar.TRCONSULTAACUERDOTRNI.TRCONSULTAACUERDOEVTY createEjecutarTRCONSULTAACUERDOTRNITRCONSULTAACUERDOEVTY() {
        return new Ejecutar.TRCONSULTAACUERDOTRNI.TRCONSULTAACUERDOEVTY();
    }

    /**
     * Create an instance of {@link EjecutarResponse }
     * 
     */
    public EjecutarResponse createEjecutarResponse() {
        return new EjecutarResponse();
    }

    /**
     * Create an instance of {@link EjecutarResult }
     * 
     */
    public EjecutarResult createEjecutarResult() {
        return new EjecutarResult();
    }

    /**
     * Create an instance of {@link ArrayOfResponseBansefi }
     * 
     */
    public ArrayOfResponseBansefi createArrayOfResponseBansefi() {
        return new ArrayOfResponseBansefi();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.STDTRNMSJPARMV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.STDTRNMSJPARMV createResponseBansefiTRCONSULTAACUERDOTRNOSTDTRNMSJPARMV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.STDTRNMSJPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.STDTRNOPARMV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.STDTRNOPARMV createResponseBansefiTRCONSULTAACUERDOTRNOSTDTRNOPARMV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.STDTRNOPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.STDANAVMSJV.ANNUMANOTACIONESV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.STDANAVMSJV.ANNUMANOTACIONESV createResponseBansefiTRCONSULTAACUERDOTRNOSTDANAVMSJVANNUMANOTACIONESV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.STDANAVMSJV.ANNUMANOTACIONESV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.STDANAVMSJV.STDANAVMSJLS.DESCRIPANTCNV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.STDANAVMSJV.STDANAVMSJLS.DESCRIPANTCNV createResponseBansefiTRCONSULTAACUERDOTRNOSTDANAVMSJVSTDANAVMSJLSDESCRIPANTCNV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.STDANAVMSJV.STDANAVMSJLS.DESCRIPANTCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.STDANAVMSJV.STDANAVMSJLS.DESCINDPRDADV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.STDANAVMSJV.STDANAVMSJLS.DESCINDPRDADV createResponseBansefiTRCONSULTAACUERDOTRNOSTDANAVMSJVSTDANAVMSJLSDESCINDPRDADV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.STDANAVMSJV.STDANAVMSJLS.DESCINDPRDADV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.STDANAVMSJV.STDANAVMSJLS.STDDESCRCANTCNV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.STDANAVMSJV.STDANAVMSJLS.STDDESCRCANTCNV createResponseBansefiTRCONSULTAACUERDOTRNOSTDANAVMSJVSTDANAVMSJLSSTDDESCRCANTCNV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.STDANAVMSJV.STDANAVMSJLS.STDDESCRCANTCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.ACACE }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.ACACE createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZACACE() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.ACACE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.INDREPRESENTANTEV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.INDREPRESENTANTEV createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZINDREPRESENTANTEV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.INDREPRESENTANTEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.DESCRPDVV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.DESCRPDVV createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZDESCRPDVV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.DESCRPDVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.PERSONAACV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.PERSONAACV createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZPERSONAACV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.PERSONAACV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.NUMTARJETAV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.NUMTARJETAV createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZNUMTARJETAV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.NUMTARJETAV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KACDACE }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KACDACE createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKACDACE() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KACDACE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTVLISTAV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTVLISTAV createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAESTRCTVLISTAV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTVLISTAV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAKARLPKDOMV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAKARLPKDOMV createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAKARLPKDOMV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAKARLPKDOMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTRNGV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTRNGV createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAESTRCTRNGV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTRNGV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTVRNGV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTVRNGV createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAESTRCTVRNGV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTVRNGV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTCMSN1V }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTCMSN1V createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAESTRCTCMSN1V() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTCMSN1V();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KACMSNPRCTLV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KACMSNPRCTLV createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKACMSNPRCTLV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KACMSNPRCTLV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KACMSNFIJV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KACMSNFIJV createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKACMSNFIJV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KACMSNFIJV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTINT1V }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTINT1V createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAESTRCTINT1V() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTINT1V();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTINTFIJV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTINTFIJV createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAESTRCTINTFIJV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTINTFIJV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTINTVARV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTINTVARV createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAESTRCTINTVARV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAESTRCTINTVARV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTFRANQ1V }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTFRANQ1V createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAINTFRANQ1V() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTFRANQ1V();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTFRANQFIJV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTFRANQFIJV createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAINTFRANQFIJV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTFRANQFIJV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTFRANQVARV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTFRANQVARV createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAINTFRANQVARV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTFRANQVARV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTRLSPV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTRLSPV createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAINTRLSPV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAINTRLSPV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAMATRIZV }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAMATRIZV createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VKAMATRIZV() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.KAMATRIZV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.IDCCPS1V }
     * 
     */
    public ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.IDCCPS1V createResponseBansefiTRCONSULTAACUERDOTRNOTRCONSULTAACUERDOEVTZTRCONSVALMSVKAEVTZKACDAC1VIDCCPS1V() {
        return new ResponseBansefi.TRCONSULTAACUERDOTRNO.TRCONSULTAACUERDOEVTZ.TRCONSVALMSVKAEVTZ.KACDAC1V.IDCCPS1V();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSULTAACUERDOTRNI.STDTRNIPARMV }
     * 
     */
    public Ejecutar.TRCONSULTAACUERDOTRNI.STDTRNIPARMV createEjecutarTRCONSULTAACUERDOTRNISTDTRNIPARMV() {
        return new Ejecutar.TRCONSULTAACUERDOTRNI.STDTRNIPARMV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSULTAACUERDOTRNI.TRCONSULTAACUERDOEVTY.ACACP }
     * 
     */
    public Ejecutar.TRCONSULTAACUERDOTRNI.TRCONSULTAACUERDOEVTY.ACACP createEjecutarTRCONSULTAACUERDOTRNITRCONSULTAACUERDOEVTYACACP() {
        return new Ejecutar.TRCONSULTAACUERDOTRNI.TRCONSULTAACUERDOEVTY.ACACP();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSULTAACUERDOTRNI.TRCONSULTAACUERDOEVTY.ACINDCONSUACV }
     * 
     */
    public Ejecutar.TRCONSULTAACUERDOTRNI.TRCONSULTAACUERDOEVTY.ACINDCONSUACV createEjecutarTRCONSULTAACUERDOTRNITRCONSULTAACUERDOEVTYACINDCONSUACV() {
        return new Ejecutar.TRCONSULTAACUERDOTRNI.TRCONSULTAACUERDOEVTY.ACINDCONSUACV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSULTAACUERDOTRNI.TRCONSULTAACUERDOEVTY.ACINDPROCEDEGESTIONV }
     * 
     */
    public Ejecutar.TRCONSULTAACUERDOTRNI.TRCONSULTAACUERDOEVTY.ACINDPROCEDEGESTIONV createEjecutarTRCONSULTAACUERDOTRNITRCONSULTAACUERDOEVTYACINDPROCEDEGESTIONV() {
        return new Ejecutar.TRCONSULTAACUERDOTRNI.TRCONSULTAACUERDOEVTY.ACINDPROCEDEGESTIONV();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EjecutarResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://BansefiNSS/WebServicesNSS/TR_CONSULTA_ACUERDO_TRN", name = "EjecutarResult")
    public JAXBElement<EjecutarResult> createEjecutarResult(EjecutarResult value) {
        return new JAXBElement<EjecutarResult>(_EjecutarResult_QNAME, EjecutarResult.class, null, value);
    }

}
