package mx.babel.bansefi.banksystem.response.consultacuenta;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2015-04-23T17:23:56.991-05:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_CONSULTA_ACUERDO_TRN", name = "SoapPort")
@XmlSeeAlso({ObjectFactory.class})
public interface SoapPort {

    @WebResult(name = "EjecutarResult", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_CONSULTA_ACUERDO_TRN")
    @RequestWrapper(localName = "Ejecutar", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_CONSULTA_ACUERDO_TRN", className = "mx.babel.bansefi.banksystem.cuentas.webservices.consultacuenta.Ejecutar")
    @WebMethod(operationName = "Ejecutar", action = "http://10.200.14.110:3300/WebServicesNSS/TR_CONSULT/Ejecutar")
    @ResponseWrapper(localName = "EjecutarResponse", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_CONSULTA_ACUERDO_TRN", className = "mx.babel.bansefi.banksystem.cuentas.webservices.consultacuenta.EjecutarResponse")
    public mx.babel.bansefi.banksystem.response.consultacuenta.EjecutarResult ejecutar(
        @WebParam(name = "TR_CONSULTA_ACUERDO_TRN_I", targetNamespace = "http://BansefiNSS/WebServicesNSS/TR_CONSULTA_ACUERDO_TRN")
        mx.babel.bansefi.banksystem.response.consultacuenta.Ejecutar.TRCONSULTAACUERDOTRNI trCONSULTAACUERDOTRNI
    );
}