
package mx.babel.bansefi.banksystem.response.modificacionempleado;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bansefinss.webservicesnss.tr_modif_empl_trn package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EjecutarResult_QNAME = new QName("http://BansefiNSS/WebServicesNSS/TR_MODIF_EMPL_TRN", "EjecutarResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bansefinss.webservicesnss.tr_modif_empl_trn
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ejecutar }
     * 
     */
    public Ejecutar createEjecutar() {
        return new Ejecutar();
    }

    /**
     * Create an instance of {@link ResponseBansefi }
     * 
     */
    public ResponseBansefi createResponseBansefi() {
        return new ResponseBansefi();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRMODIFEMPLTRNO }
     * 
     */
    public ResponseBansefi.TRMODIFEMPLTRNO createResponseBansefiTRMODIFEMPLTRNO() {
        return new ResponseBansefi.TRMODIFEMPLTRNO();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRMODIFEMPLTRNO.TRMODIFEMPLEVTZ }
     * 
     */
    public ResponseBansefi.TRMODIFEMPLTRNO.TRMODIFEMPLEVTZ createResponseBansefiTRMODIFEMPLTRNOTRMODIFEMPLEVTZ() {
        return new ResponseBansefi.TRMODIFEMPLTRNO.TRMODIFEMPLEVTZ();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI createEjecutarTRMODIFEMPLTRNI() {
        return new Ejecutar.TRMODIFEMPLTRNI();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTY() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PECOMPARTIRDOMICOBJTRDV }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PECOMPARTIRDOMICOBJTRDV createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYPECOMPARTIRDOMICOBJTRDV() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PECOMPARTIRDOMICOBJTRDV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYDRDMDPOBJTRDV() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEALTAINDVOBJTRDV }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEALTAINDVOBJTRDV createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYPEALTAINDVOBJTRDV() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEALTAINDVOBJTRDV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFEPEMPLV() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVV() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV();
    }

    /**
     * Create an instance of {@link EjecutarResponse }
     * 
     */
    public EjecutarResponse createEjecutarResponse() {
        return new EjecutarResponse();
    }

    /**
     * Create an instance of {@link EjecutarResult }
     * 
     */
    public EjecutarResult createEjecutarResult() {
        return new EjecutarResult();
    }

    /**
     * Create an instance of {@link ArrayOfResponseBansefi }
     * 
     */
    public ArrayOfResponseBansefi createArrayOfResponseBansefi() {
        return new ArrayOfResponseBansefi();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRMODIFEMPLTRNO.STDTRNMSJPARMV }
     * 
     */
    public ResponseBansefi.TRMODIFEMPLTRNO.STDTRNMSJPARMV createResponseBansefiTRMODIFEMPLTRNOSTDTRNMSJPARMV() {
        return new ResponseBansefi.TRMODIFEMPLTRNO.STDTRNMSJPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRMODIFEMPLTRNO.STDTRNOPARMV }
     * 
     */
    public ResponseBansefi.TRMODIFEMPLTRNO.STDTRNOPARMV createResponseBansefiTRMODIFEMPLTRNOSTDTRNOPARMV() {
        return new ResponseBansefi.TRMODIFEMPLTRNO.STDTRNOPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.PERIDENNOMBGRV }
     * 
     */
    public ResponseBansefi.TRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.PERIDENNOMBGRV createResponseBansefiTRMODIFEMPLTRNOTRMODIFEMPLEVTZPERIDENNOMBGRV() {
        return new ResponseBansefi.TRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.PERIDENNOMBGRV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.DRDOMICP }
     * 
     */
    public ResponseBansefi.TRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.DRDOMICP createResponseBansefiTRMODIFEMPLTRNOTRMODIFEMPLEVTZDRDOMICP() {
        return new ResponseBansefi.TRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.DRDOMICP();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.PEPERSP }
     * 
     */
    public ResponseBansefi.TRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.PEPERSP createResponseBansefiTRMODIFEMPLTRNOTRMODIFEMPLEVTZPEPERSP() {
        return new ResponseBansefi.TRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.PEPERSP();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.CLAVEEMPLEADOV }
     * 
     */
    public ResponseBansefi.TRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.CLAVEEMPLEADOV createResponseBansefiTRMODIFEMPLTRNOTRMODIFEMPLEVTZCLAVEEMPLEADOV() {
        return new ResponseBansefi.TRMODIFEMPLTRNO.TRMODIFEMPLEVTZ.CLAVEEMPLEADOV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.STDTRNIPARMV }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.STDTRNIPARMV createEjecutarTRMODIFEMPLTRNISTDTRNIPARMV() {
        return new Ejecutar.TRMODIFEMPLTRNI.STDTRNIPARMV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.EPPEDPOBJTRDV }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.EPPEDPOBJTRDV createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYEPPEDPOBJTRDV() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.EPPEDPOBJTRDV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.EPEMPLP }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.EPEMPLP createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYEPEMPLP() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.EPEMPLP();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.AGLOCALIDADNOCODV }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.AGLOCALIDADNOCODV createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYAGLOCALIDADNOCODV() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.AGLOCALIDADNOCODV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMASDIRV }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMASDIRV createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMASDIRV() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMASDIRV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEPERSINDCLIENTEV }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEPERSINDCLIENTEV createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYPEPERSINDCLIENTEV() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEPERSINDCLIENTEV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDAVISOFALLEC }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDAVISOFALLEC createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDAVISOFALLEC() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDAVISOFALLEC();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDAVISOSITECO }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDAVISOSITECO createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDAVISOSITECO() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDAVISOSITECO();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDAVISOTARJRES }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDAVISOTARJRES createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDAVISOTARJRES() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDAVISOTARJRES();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PECOMPARTIRDOMICV }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PECOMPARTIRDOMICV createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYPECOMPARTIRDOMICV() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PECOMPARTIRDOMICV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PECOMPARTIRDOMICOBJTRDV.CODPERSRLDIRV }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PECOMPARTIRDOMICOBJTRDV.CODPERSRLDIRV createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYPECOMPARTIRDOMICOBJTRDVCODPERSRLDIRV() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PECOMPARTIRDOMICOBJTRDV.CODPERSRLDIRV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.CODPERSRLDIRV }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.CODPERSRLDIRV createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYDRDMDPOBJTRDVCODPERSRLDIRV() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.CODPERSRLDIRV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.CODARGEODOMICILIOV }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.CODARGEODOMICILIOV createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYDRDMDPOBJTRDVCODARGEODOMICILIOV() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.CODARGEODOMICILIOV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.NUMARGEODOMICILIOV }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.NUMARGEODOMICILIOV createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYDRDMDPOBJTRDVNUMARGEODOMICILIOV() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.NUMARGEODOMICILIOV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.COMPDOMICV }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.COMPDOMICV createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYDRDMDPOBJTRDVCOMPDOMICV() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.COMPDOMICV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.DRELCTRV }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.DRELCTRV createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYDRDMDPOBJTRDVDRELCTRV() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.DRDMDPOBJTRDV.DRELCTRV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEALTAINDVOBJTRDV.PERLARGEONUMV }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEALTAINDVOBJTRDV.PERLARGEONUMV createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYPEALTAINDVOBJTRDVPERLARGEONUMV() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEALTAINDVOBJTRDV.PERLARGEONUMV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEALTAINDVOBJTRDV.AGLOCNOCODNUMV }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEALTAINDVOBJTRDV.AGLOCNOCODNUMV createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYPEALTAINDVOBJTRDVAGLOCNOCODNUMV() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.PEALTAINDVOBJTRDV.AGLOCNOCODNUMV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPEMPLINS }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPEMPLINS createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFEPEMPLVINDEPEMPLINS() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPEMPLINS();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPEMPLUPD }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPEMPLUPD createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFEPEMPLVINDEPEMPLUPD() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPEMPLUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPCARGOEMPLUPD }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPCARGOEMPLUPD createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFEPEMPLVINDEPCARGOEMPLUPD() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPCARGOEMPLUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPEMPLRLCENTUPD }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPEMPLRLCENTUPD createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFEPEMPLVINDEPEMPLRLCENTUPD() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFEPEMPLV.INDEPEMPLRLCENTUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEPERSUPD }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEPERSUPD createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPEPERSUPD() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEPERSUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEINDVUPD }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEINDVUPD createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPEINDVUPD() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEINDVUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEIDEXTUPD }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEIDEXTUPD createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPEIDEXTUPD() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEIDEXTUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEIDEXTUPDDEL }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEIDEXTUPDDEL createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPEIDEXTUPDDEL() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEIDEXTUPDDEL();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEIDEXTINS }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEIDEXTINS createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPEIDEXTINS() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEIDEXTINS();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEACTPROFINDVINS }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEACTPROFINDVINS createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPEACTPROFINDVINS() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEACTPROFINDVINS();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEOTROCNAEUPD }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEOTROCNAEUPD createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPEOTROCNAEUPD() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEOTROCNAEUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEOTROCNAEINS }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEOTROCNAEINS createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPEOTROCNAEINS() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEOTROCNAEINS();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPD }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPD createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPECPCDADLGLINDVUPD() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPDDEL }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPDDEL createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPECPCDADLGLINDVUPDDEL() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVUPDDEL();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVINS }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVINS createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPECPCDADLGLINDVINS() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPECPCDADLGLINDVINS();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPESITECONUPD }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPESITECONUPD createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPESITECONUPD() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPESITECONUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPESITECONINS }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPESITECONINS createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPESITECONINS() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPESITECONINS();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOUPD }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOUPD createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPEPERSRLARGEOUPD() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOINS }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOINS createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPEPERSRLARGEOINS() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEPERSRLARGEOINS();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDAGLOCALIDADNOCODINS }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDAGLOCALIDADNOCODINS createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDAGLOCALIDADNOCODINS() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDAGLOCALIDADNOCODINS();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEINDVFRDLNTAUPD }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEINDVFRDLNTAUPD createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDPEINDVFRDLNTAUPD() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDPEINDVFRDLNTAUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDCLCLIENTINS }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDCLCLIENTINS createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDCLCLIENTINS() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDCLCLIENTINS();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICCOMPARTIR }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICCOMPARTIR createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDDRDOMICCOMPARTIR() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICCOMPARTIR();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICUPD }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICUPD createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDDRDOMICUPD() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICUPD();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICINS }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICINS createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDDRDOMICINS() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICINS();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICUPDCOMPARTIR }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICUPDCOMPARTIR createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDDRDOMICUPDCOMPARTIR() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDDRDOMICUPDCOMPARTIR();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDSOLOMODIDOMIC }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDSOLOMODIDOMIC createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDSOLOMODIDOMIC() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDSOLOMODIDOMIC();
    }

    /**
     * Create an instance of {@link Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDMODINUMDIRPRAL }
     * 
     */
    public Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDMODINUMDIRPRAL createEjecutarTRMODIFEMPLTRNITRMODIFEMPLEVTYINDMODIFCLINDVVINDMODINUMDIRPRAL() {
        return new Ejecutar.TRMODIFEMPLTRNI.TRMODIFEMPLEVTY.INDMODIFCLINDVV.INDMODINUMDIRPRAL();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EjecutarResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://BansefiNSS/WebServicesNSS/TR_MODIF_EMPL_TRN", name = "EjecutarResult")
    public JAXBElement<EjecutarResult> createEjecutarResult(EjecutarResult value) {
        return new JAXBElement<EjecutarResult>(_EjecutarResult_QNAME, EjecutarResult.class, null, value);
    }

}
