
package mx.babel.bansefi.banksystem.cuentas.webservices.constituircuenta;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.babel.bansefi.banksystem.cuentas.webservices.constituircuenta package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName EJECUTAR_RESULT_QNAME = new QName(mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_CONSTI_TOTAL_AC_TRN", "EjecutarResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.babel.bansefi.banksystem.cuentas.webservices.constituircuenta
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ejecutar }
     * 
     */
    public Ejecutar createEjecutar() {
        return new Ejecutar();
    }

    /**
     * Create an instance of {@link ResponseBansefi }
     * 
     */
    public ResponseBansefi createResponseBansefi() {
        return new ResponseBansefi();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO createResponseBansefiTRCONSTITOTALACTRNO() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.STDAUTORIZAV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.STDAUTORIZAV createResponseBansefiTRCONSTITOTALACTRNOSTDAUTORIZAV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.STDAUTORIZAV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZ() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.GACRESULTOPERV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.GACRESULTOPERV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVGACRESULTOPERV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.GACRESULTOPERV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLSUBVV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVACPSVCONVV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLINTERESV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLINTERESVLIQHLTRAMOAPLICV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLCOMISIONV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLCOMISIONVLIQAFAPNTECMSNLST() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLCOMISIONVLIQAFAPNTECMSNLSTLIQAFAPNTECMSNE() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVIDFRACASOCCV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.IDFRLINEAAVALV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.IDFRLINEAAVALV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVIDFRLINEAAVALV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.IDFRLINEAAVALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLSDOOPCIONV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLSDOOPCIONV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVHLSDOOPCIONV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLSDOOPCIONV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLSDOOPCIONV.HLSDOLST }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLSDOOPCIONV.HLSDOLST createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVHLSDOOPCIONVHLSDOLST() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLSDOOPCIONV.HLSDOLST();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVHLHCOLIQEV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLINFADICLST }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLINFADICLST createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVHLHCOLIQEVHLINFADICLST() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLINFADICLST();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLSDOLST }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLSDOLST createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVHLHCOLIQEVHLSDOLST() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLSDOLST();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.GACRESULTOPERV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.GACRESULTOPERV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVGACRESULTOPERV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.GACRESULTOPERV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVGTOSNOTARIOV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVGTOSNOTARIOV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVGTOSNOTARIOV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVGTOSNOTARIOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLSUBVV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVACVACPSVCONVV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLINTERESV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLINTERESVLIQHLTRAMOAPLICV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLCOMISIONV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLCOMISIONVLIQAFAPNTECMSNLST() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLCOMISIONVLIQAFAPNTECMSNLSTLIQAFAPNTECMSNE() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.IDFRLINEAAVALV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.IDFRLINEAAVALV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVIDFRLINEAAVALV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.IDFRLINEAAVALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVIDFRACASOCCV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVIDFRACASOCCV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVIDFRACASOCCV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVIDFRACASOCCV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVAFCONSTITV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVAFCONSTITV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVAFCONSTITV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVAFCONSTITV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVIMPTESDIVISIONV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLSDOOPCIONV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLSDOOPCIONV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVHLSDOOPCIONV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLSDOOPCIONV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLSDOOPCIONV.HLSDOLST }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLSDOOPCIONV.HLSDOLST createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVHLSDOOPCIONVHLSDOLST() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLSDOOPCIONV.HLSDOLST();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLHCOLIQEV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLHCOLIQEV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVHLHCOLIQEV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLHCOLIQEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLINFADICLST }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLINFADICLST createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVHLHCOLIQEVHLINFADICLST() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLINFADICLST();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLSDOLST }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLSDOLST createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVHLHCOLIQEVHLSDOLST() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLSDOLST();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSTITOTALACTRNI }
     * 
     */
    public Ejecutar.TRCONSTITOTALACTRNI createEjecutarTRCONSTITOTALACTRNI() {
        return new Ejecutar.TRCONSTITOTALACTRNI();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSTITOTALACTRNI.STDAUTORIZAV }
     * 
     */
    public Ejecutar.TRCONSTITOTALACTRNI.STDAUTORIZAV createEjecutarTRCONSTITOTALACTRNISTDAUTORIZAV() {
        return new Ejecutar.TRCONSTITOTALACTRNI.STDAUTORIZAV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY }
     * 
     */
    public Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY createEjecutarTRCONSTITOTALACTRNITRCONSTITOTALACEVTY() {
        return new Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY();
    }

    /**
     * Create an instance of {@link EjecutarResponse }
     * 
     */
    public EjecutarResponse createEjecutarResponse() {
        return new EjecutarResponse();
    }

    /**
     * Create an instance of {@link EjecutarResult }
     * 
     */
    public EjecutarResult createEjecutarResult() {
        return new EjecutarResult();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.STDTRNMSJPARMV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.STDTRNMSJPARMV createResponseBansefiTRCONSTITOTALACTRNOSTDTRNMSJPARMV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.STDTRNMSJPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.STDTRNOPARMV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.STDTRNOPARMV createResponseBansefiTRCONSTITOTALACTRNOSTDTRNOPARMV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.STDTRNOPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.RESPUESTASINCRONAV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.RESPUESTASINCRONAV createResponseBansefiTRCONSTITOTALACTRNORESPUESTASINCRONAV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.RESPUESTASINCRONAV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.NROLLAMADAV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.NROLLAMADAV createResponseBansefiTRCONSTITOTALACTRNONROLLAMADAV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.NROLLAMADAV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.ACUERDO2V }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.ACUERDO2V createResponseBansefiTRCONSTITOTALACTRNOACUERDO2V() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.ACUERDO2V();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.STDAUTORIZAV.ARAUTREMOTAP }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.STDAUTORIZAV.ARAUTREMOTAP createResponseBansefiTRCONSTITOTALACTRNOSTDAUTORIZAVARAUTREMOTAP() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.STDAUTORIZAV.ARAUTREMOTAP();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.STDAUTORIZAV.ARTRNMSJPARMV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.STDAUTORIZAV.ARTRNMSJPARMV createResponseBansefiTRCONSTITOTALACTRNOSTDAUTORIZAVARTRNMSJPARMV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.STDAUTORIZAV.ARTRNMSJPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.STDAUTORIZAV.STDTARGETTERMINALV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.STDAUTORIZAV.STDTARGETTERMINALV createResponseBansefiTRCONSTITOTALACTRNOSTDAUTORIZAVSTDTARGETTERMINALV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.STDAUTORIZAV.STDTARGETTERMINALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.STDAUTORIZAV.ARIDSALTADOV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.STDAUTORIZAV.ARIDSALTADOV createResponseBansefiTRCONSTITOTALACTRNOSTDAUTORIZAVARIDSALTADOV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.STDAUTORIZAV.ARIDSALTADOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.ACDATOSV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.ACDATOSV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZACDATOSV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.ACDATOSV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.PSVIMPAUTV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.PSVIMPAUTV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZPSVIMPAUTV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.PSVIMPAUTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.PSVERRORV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.PSVERRORV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZPSVERRORV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.PSVERRORV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.NUMULTFCTRALEASV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.NUMULTFCTRALEASV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZNUMULTFCTRALEASV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.NUMULTFCTRALEASV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVIMPTOTALV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVIMPTOTALV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVIMPTOTALV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVIMPTOTALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVSDORSGOAVV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVSDORSGOAVV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVSDORSGOAVV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVSDORSGOAVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVSDOPDTEVTOV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVSDOPDTEVTOV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVSDOPDTEVTOV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVSDOPDTEVTOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVIMPLIMV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVIMPLIMV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVIMPLIMV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVIMPLIMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVIMPDEUDAIMPAGV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVIMPDEUDAIMPAGV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVIMPDEUDAIMPAGV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVIMPDEUDAIMPAGV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVINDSUBVENCV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVINDSUBVENCV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVINDSUBVENCV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVINDSUBVENCV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVINDSUBDIVV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVINDSUBDIVV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVINDSUBDIVV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVINDSUBDIVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVINDMIXTOV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVINDMIXTOV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVINDMIXTOV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVINDMIXTOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVAFAPUNTESV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVAFAPUNTESV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVAFAPUNTESV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVAFAPUNTESV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACLINEAGRUPOV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACLINEAGRUPOV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACLINEAGRUPOV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACLINEAGRUPOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVMODALLIQUIDV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVMODALLIQUIDV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVMODALLIQUIDV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVMODALLIQUIDV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVINDDOMICV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVINDDOMICV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVINDDOMICV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVINDDOMICV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.GACRESULTOPERV.GACIMPTENETOV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.GACRESULTOPERV.GACIMPTENETOV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVGACRESULTOPERVGACIMPTENETOV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.GACRESULTOPERV.GACIMPTENETOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.GACRESULTOPERV.GACIMPTEOPERV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.GACRESULTOPERV.GACIMPTEOPERV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVGACRESULTOPERVGACIMPTEOPERV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.GACRESULTOPERV.GACIMPTEOPERV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVTOTALSUBDOV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVTOTALSUBDOV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVTOTALSUBDOV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVTOTALSUBDOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.IDFRSBLV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.IDFRSBLV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVIDFRSBLV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.IDFRSBLV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINTERESSUBVCNV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINTERESSUBVCNV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVINTERESSUBVCNV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINTERESSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCAPITALSUBVCNV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCAPITALSUBVCNV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVCAPITALSUBVCNV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCAPITALSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFINNCSUBVCNV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFINNCSUBVCNV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVFINNCSUBVCNV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFINNCSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMASUBVCNV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMASUBVCNV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVFORMASUBVCNV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMASUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCPTOSUBVCNV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCPTOSUBVCNV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVCPTOSUBVCNV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCPTOSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCOBROANTV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCOBROANTV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVCOBROANTV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCOBROANTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINFORMASUBVCNV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINFORMASUBVCNV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVINFORMASUBVCNV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINFORMASUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMARECLAMV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMARECLAMV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVFORMARECLAMV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMARECLAMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVSUBVRECLAMABLEV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVSUBVRECLAMABLEV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVSUBVRECLAMABLEV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVSUBVRECLAMABLEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV.ACACP }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV.ACACP createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVACPSVCONVVACACP() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV.ACACP();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.ACVINTERESCTV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.ACVINTERESCTV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLINTERESVACVINTERESCTV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.ACVINTERESCTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV.HLTRAMOV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV.HLTRAMOV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLINTERESVLIQHLTRAMOAPLICVHLTRAMOV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV.HLTRAMOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVGASTOSV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVGASTOSV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLCOMISIONVACVGASTOSV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVGASTOSV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVTOTALGASEXTV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVTOTALGASEXTV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLCOMISIONVACVTOTALGASEXTV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVTOTALGASEXTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVCOMISIONV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVCOMISIONV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLCOMISIONVACVCOMISIONV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVCOMISIONV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVIMPUESTOV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVIMPUESTOV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLCOMISIONVACVIMPUESTOV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVIMPUESTOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE.LIQKTCMSNV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE.LIQKTCMSNV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVDSGLCOMISIONVLIQAFAPNTECMSNLSTLIQAFAPNTECMSNELIQKTCMSNV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE.LIQKTCMSNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV.IDFRACLV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV.IDFRACLV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVIDFRACASOCCVIDFRACLV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV.IDFRACLV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV.ACVMONEDAASOCCV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV.ACVMONEDAASOCCV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVACVIDFRACASOCCVACVMONEDAASOCCV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV.ACVMONEDAASOCCV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.IDFRLINEAAVALV.IDFRACLV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.IDFRLINEAAVALV.IDFRACLV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVIDFRLINEAAVALVIDFRACLV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.IDFRLINEAAVALV.IDFRACLV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLSDOOPCIONV.HLSDOLST.HLSDOEV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLSDOOPCIONV.HLSDOLST.HLSDOEV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVHLSDOOPCIONVHLSDOLSTHLSDOEV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLSDOOPCIONV.HLSDOLST.HLSDOEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLHCOLIQE }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLHCOLIQE createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVHLHCOLIQEVHLHCOLIQE() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLHCOLIQE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLINFADICLST.HLINFADICV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLINFADICLST.HLINFADICV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVHLHCOLIQEVHLINFADICLSTHLINFADICV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLINFADICLST.HLINFADICV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLSDOLST.HLSDOEV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLSDOLST.HLSDOEV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCANCVHLHCOLIQEVHLSDOLSTHLSDOEV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLSDOLST.HLSDOEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVIMPTOTALV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVIMPTOTALV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVIMPTOTALV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVIMPTOTALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVIMPDISPOV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVIMPDISPOV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVIMPDISPOV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVIMPDISPOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACACSUSTITUIDOV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACACSUSTITUIDOV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACACSUSTITUIDOV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACACSUSTITUIDOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.AIACRLBIE }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.AIACRLBIE createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVAIACRLBIE() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.AIACRLBIE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVINDMIXTOV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVINDMIXTOV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVINDMIXTOV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVINDMIXTOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVINDSUBVENCV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVINDSUBVENCV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVINDSUBVENCV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVINDSUBVENCV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVINDSUBDIVV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVINDSUBDIVV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVINDSUBDIVV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVINDSUBDIVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVPERIODLIQUIDV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVPERIODLIQUIDV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVPERIODLIQUIDV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVPERIODLIQUIDV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDISPONIBILIDADV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDISPONIBILIDADV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDISPONIBILIDADV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDISPONIBILIDADV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVMODALLIQUIDV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVMODALLIQUIDV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVMODALLIQUIDV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVMODALLIQUIDV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVFCHPROXLIQUIV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVFCHPROXLIQUIV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVFCHPROXLIQUIV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVFCHPROXLIQUIV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVCUOTAACTUALV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVCUOTAACTUALV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVCUOTAACTUALV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVCUOTAACTUALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVCAPITALCTV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVCAPITALCTV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVCAPITALCTV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVCAPITALCTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVENTREGAINICIALV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVENTREGAINICIALV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVENTREGAINICIALV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVENTREGAINICIALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVVALORRESIDUALV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVVALORRESIDUALV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVVALORRESIDUALV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVVALORRESIDUALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVINDDOMICV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVINDDOMICV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVINDDOMICV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVINDDOMICV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.GACRESULTOPERV.GACIMPTENETOV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.GACRESULTOPERV.GACIMPTENETOV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVGACRESULTOPERVGACIMPTENETOV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.GACRESULTOPERV.GACIMPTENETOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.GACRESULTOPERV.GACIMPTEOPERV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.GACRESULTOPERV.GACIMPTEOPERV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVGACRESULTOPERVGACIMPTEOPERV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.GACRESULTOPERV.GACIMPTEOPERV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVGTOSNOTARIOV.AFAPNTEE }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVGTOSNOTARIOV.AFAPNTEE createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVGTOSNOTARIOVAFAPNTEE() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVGTOSNOTARIOV.AFAPNTEE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVTOTALSUBDOV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVTOTALSUBDOV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLSUBVVACVTOTALSUBDOV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVTOTALSUBDOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.IDFRSBLV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.IDFRSBLV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVIDFRSBLV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.IDFRSBLV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINTERESSUBVCNV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINTERESSUBVCNV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVACVINTERESSUBVCNV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINTERESSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCAPITALSUBVCNV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCAPITALSUBVCNV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVACVCAPITALSUBVCNV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCAPITALSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFINNCSUBVCNV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFINNCSUBVCNV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVACVFINNCSUBVCNV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFINNCSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMASUBVCNV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMASUBVCNV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVACVFORMASUBVCNV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMASUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCPTOSUBVCNV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCPTOSUBVCNV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVACVCPTOSUBVCNV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCPTOSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCOBROANTV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCOBROANTV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVACVCOBROANTV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCOBROANTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINFORMASUBVCNV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINFORMASUBVCNV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVACVINFORMASUBVCNV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINFORMASUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMARECLAMV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMARECLAMV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVACVFORMARECLAMV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMARECLAMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVSUBVRECLAMABLEV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVSUBVRECLAMABLEV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVACVSUBVRECLAMABLEV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVSUBVRECLAMABLEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV.ACACP }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV.ACACP createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLSUBVVACVLIQSUBVCNVACVACPSVCONVVACACP() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV.ACACP();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV.ACVINTERESCTV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV.ACVINTERESCTV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLINTERESVACVINTERESCTV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV.ACVINTERESCTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV.HLTRAMOV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV.HLTRAMOV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLINTERESVLIQHLTRAMOAPLICVHLTRAMOV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV.HLTRAMOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVGASTOSV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVGASTOSV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLCOMISIONVACVGASTOSV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVGASTOSV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVTOTALGASEXTV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVTOTALGASEXTV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLCOMISIONVACVTOTALGASEXTV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVTOTALGASEXTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVCOMISIONV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVCOMISIONV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLCOMISIONVACVCOMISIONV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVCOMISIONV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVIMPUESTOV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVIMPUESTOV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLCOMISIONVACVIMPUESTOV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.ACVIMPUESTOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE.LIQKTCMSNV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE.LIQKTCMSNV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVDSGLCOMISIONVLIQAFAPNTECMSNLSTLIQAFAPNTECMSNELIQKTCMSNV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE.LIQKTCMSNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.IDFRLINEAAVALV.IDFRACLV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.IDFRLINEAAVALV.IDFRACLV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVIDFRLINEAAVALVIDFRACLV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.IDFRLINEAAVALV.IDFRACLV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVIDFRACASOCCV.IDFRACLV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVIDFRACASOCCV.IDFRACLV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVIDFRACASOCCVIDFRACLV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVIDFRACASOCCV.IDFRACLV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVIDFRACASOCCV.ACVMONEDAASOCCV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVIDFRACASOCCV.ACVMONEDAASOCCV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVIDFRACASOCCVACVMONEDAASOCCV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVIDFRACASOCCV.ACVMONEDAASOCCV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVAFCONSTITV.AFAPNTEE }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVAFCONSTITV.AFAPNTEE createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVACVAFCONSTITVAFAPNTEE() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.ACVAFCONSTITV.AFAPNTEE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV.ACVDISPBLESUBDVV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV.ACVDISPBLESUBDVV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVIMPTESDIVISIONVACVDISPBLESUBDVV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV.ACVDISPBLESUBDVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV.ACVLIMITESUBDVV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV.ACVLIMITESUBDVV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVIMPTESDIVISIONVACVLIMITESUBDVV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV.ACVLIMITESUBDVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV.AMORTIZSUBDVV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV.AMORTIZSUBDVV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVIMPTESDIVISIONVAMORTIZSUBDVV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.IMPTESDIVISIONV.AMORTIZSUBDVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLSDOOPCIONV.HLSDOLST.HLSDOEV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLSDOOPCIONV.HLSDOLST.HLSDOEV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVHLSDOOPCIONVHLSDOLSTHLSDOEV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLSDOOPCIONV.HLSDOLST.HLSDOEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLHCOLIQE }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLHCOLIQE createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVHLHCOLIQEVHLHCOLIQE() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLHCOLIQE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLINFADICLST.HLINFADICV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLINFADICLST.HLINFADICV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVHLHCOLIQEVHLINFADICLSTHLINFADICV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLINFADICLST.HLINFADICV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLSDOLST.HLSDOEV }
     * 
     */
    public ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLSDOLST.HLSDOEV createResponseBansefiTRCONSTITOTALACTRNOTRCONSTITOTALACEVTZTRSIMULCONSTVHLHCOLIQEVHLSDOLSTHLSDOEV() {
        return new ResponseBansefi.TRCONSTITOTALACTRNO.TRCONSTITOTALACEVTZ.TRSIMULCONSTV.HLHCOLIQEV.HLSDOLST.HLSDOEV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSTITOTALACTRNI.STDTRNIPARMV }
     * 
     */
    public Ejecutar.TRCONSTITOTALACTRNI.STDTRNIPARMV createEjecutarTRCONSTITOTALACTRNISTDTRNIPARMV() {
        return new Ejecutar.TRCONSTITOTALACTRNI.STDTRNIPARMV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSTITOTALACTRNI.RESPUESTASINCRONAV }
     * 
     */
    public Ejecutar.TRCONSTITOTALACTRNI.RESPUESTASINCRONAV createEjecutarTRCONSTITOTALACTRNIRESPUESTASINCRONAV() {
        return new Ejecutar.TRCONSTITOTALACTRNI.RESPUESTASINCRONAV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSTITOTALACTRNI.NROLLAMADAV }
     * 
     */
    public Ejecutar.TRCONSTITOTALACTRNI.NROLLAMADAV createEjecutarTRCONSTITOTALACTRNINROLLAMADAV() {
        return new Ejecutar.TRCONSTITOTALACTRNI.NROLLAMADAV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSTITOTALACTRNI.STDAUTORIZAV.ARAUTREMOTAP }
     * 
     */
    public Ejecutar.TRCONSTITOTALACTRNI.STDAUTORIZAV.ARAUTREMOTAP createEjecutarTRCONSTITOTALACTRNISTDAUTORIZAVARAUTREMOTAP() {
        return new Ejecutar.TRCONSTITOTALACTRNI.STDAUTORIZAV.ARAUTREMOTAP();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSTITOTALACTRNI.STDAUTORIZAV.ARTRNMSJPARMV }
     * 
     */
    public Ejecutar.TRCONSTITOTALACTRNI.STDAUTORIZAV.ARTRNMSJPARMV createEjecutarTRCONSTITOTALACTRNISTDAUTORIZAVARTRNMSJPARMV() {
        return new Ejecutar.TRCONSTITOTALACTRNI.STDAUTORIZAV.ARTRNMSJPARMV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSTITOTALACTRNI.STDAUTORIZAV.STDTARGETTERMINALV }
     * 
     */
    public Ejecutar.TRCONSTITOTALACTRNI.STDAUTORIZAV.STDTARGETTERMINALV createEjecutarTRCONSTITOTALACTRNISTDAUTORIZAVSTDTARGETTERMINALV() {
        return new Ejecutar.TRCONSTITOTALACTRNI.STDAUTORIZAV.STDTARGETTERMINALV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSTITOTALACTRNI.STDAUTORIZAV.ARIDSALTADOV }
     * 
     */
    public Ejecutar.TRCONSTITOTALACTRNI.STDAUTORIZAV.ARIDSALTADOV createEjecutarTRCONSTITOTALACTRNISTDAUTORIZAVARIDSALTADOV() {
        return new Ejecutar.TRCONSTITOTALACTRNI.STDAUTORIZAV.ARIDSALTADOV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.PSVERRORV }
     * 
     */
    public Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.PSVERRORV createEjecutarTRCONSTITOTALACTRNITRCONSTITOTALACEVTYPSVERRORV() {
        return new Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.PSVERRORV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.PSVIMPAUTV }
     * 
     */
    public Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.PSVIMPAUTV createEjecutarTRCONSTITOTALACTRNITRCONSTITOTALACEVTYPSVIMPAUTV() {
        return new Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.PSVIMPAUTV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.ACACP }
     * 
     */
    public Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.ACACP createEjecutarTRCONSTITOTALACTRNITRCONSTITOTALACEVTYACACP() {
        return new Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.ACACP();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.FECHAV }
     * 
     */
    public Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.FECHAV createEjecutarTRCONSTITOTALACTRNITRCONSTITOTALACEVTYFECHAV() {
        return new Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.FECHAV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.ACVTIPOCOBROV }
     * 
     */
    public Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.ACVTIPOCOBROV createEjecutarTRCONSTITOTALACTRNITRCONSTITOTALACEVTYACVTIPOCOBROV() {
        return new Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.ACVTIPOCOBROV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.ACVLIMCONCEDIDOV }
     * 
     */
    public Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.ACVLIMCONCEDIDOV createEjecutarTRCONSTITOTALACTRNITRCONSTITOTALACEVTYACVLIMCONCEDIDOV() {
        return new Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.ACVLIMCONCEDIDOV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.RXACRLACP }
     * 
     */
    public Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.RXACRLACP createEjecutarTRCONSTITOTALACTRNITRCONSTITOTALACEVTYRXACRLACP() {
        return new Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.RXACRLACP();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.ACCUADROIRREGV }
     * 
     */
    public Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.ACCUADROIRREGV createEjecutarTRCONSTITOTALACTRNITRCONSTITOTALACEVTYACCUADROIRREGV() {
        return new Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.ACCUADROIRREGV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.SITIRREGV }
     * 
     */
    public Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.SITIRREGV createEjecutarTRCONSTITOTALACTRNITRCONSTITOTALACEVTYSITIRREGV() {
        return new Ejecutar.TRCONSTITOTALACTRNI.TRCONSTITOTALACEVTY.SITIRREGV();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EjecutarResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_CONSTI_TOTAL_AC_TRN", name = "EjecutarResult")
    public JAXBElement<EjecutarResult> createEjecutarResult(EjecutarResult value) {
        return new JAXBElement<EjecutarResult>(EJECUTAR_RESULT_QNAME, EjecutarResult.class, null, value);
    }

}
