
package mx.babel.bansefi.banksystem.cuentas.webservices.cancelacionacuerdo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.babel.bansefi.banksystem.cuentas.webservices.cancelacionacuerdo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName EJECUTARRESULT_QNAME = new QName(mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_CANCE_TOTAL_AC_TRN", "EjecutarResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.babel.bansefi.banksystem.cuentas.webservices.cancelacionacuerdo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ejecutar }
     * 
     */
    public Ejecutar createEjecutar() {
        return new Ejecutar();
    }

    /**
     * Create an instance of {@link ResponseBansefi }
     * 
     */
    public ResponseBansefi createResponseBansefi() {
        return new ResponseBansefi();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO createResponseBansefiTRCANCETOTALACTRNO() {
        return new ResponseBansefi.TRCANCETOTALACTRNO();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.STDAUTORIZAV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.STDAUTORIZAV createResponseBansefiTRCANCETOTALACTRNOSTDAUTORIZAV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.STDAUTORIZAV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZ() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.INFRECIBOBANSEFIV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.INFRECIBOBANSEFIV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZINFRECIBOBANSEFIV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.INFRECIBOBANSEFIV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.GACRESULTOPERV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.GACRESULTOPERV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVGACRESULTOPERV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.GACRESULTOPERV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLSUBVV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVACPSVCONVV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLINTERESV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLINTERESVLIQHLTRAMOAPLICV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLCOMISIONV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLCOMISIONVLIQAFAPNTECMSNLST() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLCOMISIONVLIQAFAPNTECMSNLSTLIQAFAPNTECMSNE() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVIDFRACASOCCV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.IDFRLINEAAVALV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.IDFRLINEAAVALV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVIDFRLINEAAVALV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.IDFRLINEAAVALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLSDOOPCIONV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLSDOOPCIONV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVHLSDOOPCIONV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLSDOOPCIONV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLSDOOPCIONV.HLSDOLST }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLSDOOPCIONV.HLSDOLST createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVHLSDOOPCIONVHLSDOLST() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLSDOOPCIONV.HLSDOLST();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVHLHCOLIQEV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLINFADICLST }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLINFADICLST createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVHLHCOLIQEVHLINFADICLST() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLINFADICLST();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLSDOLST }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLSDOLST createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVHLHCOLIQEVHLSDOLST() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLSDOLST();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVAFAPUNTESV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVAFAPUNTESV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVAFAPUNTESV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVAFAPUNTESV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCANCETOTALACTRNI }
     * 
     */
    public Ejecutar.TRCANCETOTALACTRNI createEjecutarTRCANCETOTALACTRNI() {
        return new Ejecutar.TRCANCETOTALACTRNI();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCANCETOTALACTRNI.STDAUTORIZAV }
     * 
     */
    public Ejecutar.TRCANCETOTALACTRNI.STDAUTORIZAV createEjecutarTRCANCETOTALACTRNISTDAUTORIZAV() {
        return new Ejecutar.TRCANCETOTALACTRNI.STDAUTORIZAV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY }
     * 
     */
    public Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY createEjecutarTRCANCETOTALACTRNITRCANCETOTALACEVTY() {
        return new Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY();
    }

    /**
     * Create an instance of {@link EjecutarResponse }
     * 
     */
    public EjecutarResponse createEjecutarResponse() {
        return new EjecutarResponse();
    }

    /**
     * Create an instance of {@link EjecutarResult }
     * 
     */
    public EjecutarResult createEjecutarResult() {
        return new EjecutarResult();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.STDTRNMSJPARMV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.STDTRNMSJPARMV createResponseBansefiTRCANCETOTALACTRNOSTDTRNMSJPARMV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.STDTRNMSJPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.STDTRNOPARMV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.STDTRNOPARMV createResponseBansefiTRCANCETOTALACTRNOSTDTRNOPARMV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.STDTRNOPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.RESPUESTASINCRONAV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.RESPUESTASINCRONAV createResponseBansefiTRCANCETOTALACTRNORESPUESTASINCRONAV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.RESPUESTASINCRONAV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.NROLLAMADAV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.NROLLAMADAV createResponseBansefiTRCANCETOTALACTRNONROLLAMADAV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.NROLLAMADAV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.ACUERDO2V }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.ACUERDO2V createResponseBansefiTRCANCETOTALACTRNOACUERDO2V() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.ACUERDO2V();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.STDAUTORIZAV.MOTIVOACCIONAUTV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.STDAUTORIZAV.MOTIVOACCIONAUTV createResponseBansefiTRCANCETOTALACTRNOSTDAUTORIZAVMOTIVOACCIONAUTV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.STDAUTORIZAV.MOTIVOACCIONAUTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.STDAUTORIZAV.ARAUTREMOTAP }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.STDAUTORIZAV.ARAUTREMOTAP createResponseBansefiTRCANCETOTALACTRNOSTDAUTORIZAVARAUTREMOTAP() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.STDAUTORIZAV.ARAUTREMOTAP();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.STDAUTORIZAV.ARTRNMSJPARMV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.STDAUTORIZAV.ARTRNMSJPARMV createResponseBansefiTRCANCETOTALACTRNOSTDAUTORIZAVARTRNMSJPARMV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.STDAUTORIZAV.ARTRNMSJPARMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.STDAUTORIZAV.STDTARGETTERMINALV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.STDAUTORIZAV.STDTARGETTERMINALV createResponseBansefiTRCANCETOTALACTRNOSTDAUTORIZAVSTDTARGETTERMINALV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.STDAUTORIZAV.STDTARGETTERMINALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.STDAUTORIZAV.ARIDSALTADOV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.STDAUTORIZAV.ARIDSALTADOV createResponseBansefiTRCANCETOTALACTRNOSTDAUTORIZAVARIDSALTADOV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.STDAUTORIZAV.ARIDSALTADOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.ACDATOSV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.ACDATOSV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZACDATOSV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.ACDATOSV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.PSVERRORV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.PSVERRORV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZPSVERRORV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.PSVERRORV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.PSVIMPAUTV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.PSVIMPAUTV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZPSVIMPAUTV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.PSVIMPAUTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.PSVNOMBRETITULARV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.PSVNOMBRETITULARV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZPSVNOMBRETITULARV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.PSVNOMBRETITULARV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.PSVULTAPNTEV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.PSVULTAPNTEV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZPSVULTAPNTEV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.PSVULTAPNTEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.INFRECIBOBANSEFIV.IMPINTERESV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.INFRECIBOBANSEFIV.IMPINTERESV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZINFRECIBOBANSEFIVIMPINTERESV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.INFRECIBOBANSEFIV.IMPINTERESV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.INFRECIBOBANSEFIV.IMPRETENCIONV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.INFRECIBOBANSEFIV.IMPRETENCIONV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZINFRECIBOBANSEFIVIMPRETENCIONV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.INFRECIBOBANSEFIV.IMPRETENCIONV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVIMPTOTALV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVIMPTOTALV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVIMPTOTALV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVIMPTOTALV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVSDORSGOAVV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVSDORSGOAVV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVSDORSGOAVV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVSDORSGOAVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVSDOPDTEVTOV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVSDOPDTEVTOV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVSDOPDTEVTOV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVSDOPDTEVTOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVIMPLIMV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVIMPLIMV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVIMPLIMV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVIMPLIMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVIMPDEUDAIMPAGV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVIMPDEUDAIMPAGV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVIMPDEUDAIMPAGV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVIMPDEUDAIMPAGV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVINDSUBVENCV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVINDSUBVENCV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVINDSUBVENCV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVINDSUBVENCV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVINDSUBDIVV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVINDSUBDIVV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVINDSUBDIVV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVINDSUBDIVV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVINDMIXTOV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVINDMIXTOV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVINDMIXTOV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVINDMIXTOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACLINEAGRUPOV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACLINEAGRUPOV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACLINEAGRUPOV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACLINEAGRUPOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVMODALLIQUIDV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVMODALLIQUIDV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVMODALLIQUIDV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVMODALLIQUIDV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVINDDOMICV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVINDDOMICV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVINDDOMICV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVINDDOMICV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.GACRESULTOPERV.GACIMPTENETOV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.GACRESULTOPERV.GACIMPTENETOV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVGACRESULTOPERVGACIMPTENETOV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.GACRESULTOPERV.GACIMPTENETOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.GACRESULTOPERV.GACIMPTEOPERV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.GACRESULTOPERV.GACIMPTEOPERV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVGACRESULTOPERVGACIMPTEOPERV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.GACRESULTOPERV.GACIMPTEOPERV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVTOTALSUBDOV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVTOTALSUBDOV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVTOTALSUBDOV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVTOTALSUBDOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.IDFRSBLV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.IDFRSBLV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVIDFRSBLV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.IDFRSBLV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINTERESSUBVCNV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINTERESSUBVCNV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVINTERESSUBVCNV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINTERESSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCAPITALSUBVCNV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCAPITALSUBVCNV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVCAPITALSUBVCNV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCAPITALSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFINNCSUBVCNV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFINNCSUBVCNV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVFINNCSUBVCNV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFINNCSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMASUBVCNV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMASUBVCNV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVFORMASUBVCNV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMASUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCPTOSUBVCNV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCPTOSUBVCNV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVCPTOSUBVCNV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCPTOSUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCOBROANTV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCOBROANTV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVCOBROANTV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVCOBROANTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINFORMASUBVCNV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINFORMASUBVCNV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVINFORMASUBVCNV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVINFORMASUBVCNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMARECLAMV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMARECLAMV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVFORMARECLAMV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVFORMARECLAMV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVSUBVRECLAMABLEV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVSUBVRECLAMABLEV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVSUBVRECLAMABLEV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVSUBVRECLAMABLEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV.ACACP }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV.ACACP createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLSUBVVACVLIQSUBVCNVACVACPSVCONVVACACP() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLSUBVV.ACVLIQSUBVCNV.ACVACPSVCONVV.ACACP();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.ACVINTERESCTV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.ACVINTERESCTV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLINTERESVACVINTERESCTV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.ACVINTERESCTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV.HLTRAMOV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV.HLTRAMOV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLINTERESVLIQHLTRAMOAPLICVHLTRAMOV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLINTERESV.LIQHLTRAMOAPLICV.HLTRAMOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVGASTOSV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVGASTOSV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLCOMISIONVACVGASTOSV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVGASTOSV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVTOTALGASEXTV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVTOTALGASEXTV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLCOMISIONVACVTOTALGASEXTV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVTOTALGASEXTV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVCOMISIONV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVCOMISIONV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLCOMISIONVACVCOMISIONV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVCOMISIONV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVIMPUESTOV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVIMPUESTOV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLCOMISIONVACVIMPUESTOV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.ACVIMPUESTOV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE.LIQKTCMSNV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE.LIQKTCMSNV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVDSGLCOMISIONVLIQAFAPNTECMSNLSTLIQAFAPNTECMSNELIQKTCMSNV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVDSGLCOMISIONV.LIQAFAPNTECMSNLST.LIQAFAPNTECMSNE.LIQKTCMSNV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV.IDFRACLV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV.IDFRACLV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVIDFRACASOCCVIDFRACLV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV.IDFRACLV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV.ACVMONEDAASOCCV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV.ACVMONEDAASOCCV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVIDFRACASOCCVACVMONEDAASOCCV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVIDFRACASOCCV.ACVMONEDAASOCCV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.IDFRLINEAAVALV.IDFRACLV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.IDFRLINEAAVALV.IDFRACLV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVIDFRLINEAAVALVIDFRACLV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.IDFRLINEAAVALV.IDFRACLV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLSDOOPCIONV.HLSDOLST.HLSDOEV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLSDOOPCIONV.HLSDOLST.HLSDOEV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVHLSDOOPCIONVHLSDOLSTHLSDOEV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLSDOOPCIONV.HLSDOLST.HLSDOEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLHCOLIQE }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLHCOLIQE createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVHLHCOLIQEVHLHCOLIQE() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLHCOLIQE();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLINFADICLST.HLINFADICV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLINFADICLST.HLINFADICV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVHLHCOLIQEVHLINFADICLSTHLINFADICV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLINFADICLST.HLINFADICV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLSDOLST.HLSDOEV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLSDOLST.HLSDOEV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVHLHCOLIQEVHLSDOLSTHLSDOEV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.HLHCOLIQEV.HLSDOLST.HLSDOEV();
    }

    /**
     * Create an instance of {@link ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVAFAPUNTESV.CONCPTAPNTEV }
     * 
     */
    public ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVAFAPUNTESV.CONCPTAPNTEV createResponseBansefiTRCANCETOTALACTRNOTRCANCETOTALACEVTZTRSIMULCANCVACVAFAPUNTESVCONCPTAPNTEV() {
        return new ResponseBansefi.TRCANCETOTALACTRNO.TRCANCETOTALACEVTZ.TRSIMULCANCV.ACVAFAPUNTESV.CONCPTAPNTEV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCANCETOTALACTRNI.STDTRNIPARMV }
     * 
     */
    public Ejecutar.TRCANCETOTALACTRNI.STDTRNIPARMV createEjecutarTRCANCETOTALACTRNISTDTRNIPARMV() {
        return new Ejecutar.TRCANCETOTALACTRNI.STDTRNIPARMV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCANCETOTALACTRNI.RESPUESTASINCRONAV }
     * 
     */
    public Ejecutar.TRCANCETOTALACTRNI.RESPUESTASINCRONAV createEjecutarTRCANCETOTALACTRNIRESPUESTASINCRONAV() {
        return new Ejecutar.TRCANCETOTALACTRNI.RESPUESTASINCRONAV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCANCETOTALACTRNI.NROLLAMADAV }
     * 
     */
    public Ejecutar.TRCANCETOTALACTRNI.NROLLAMADAV createEjecutarTRCANCETOTALACTRNINROLLAMADAV() {
        return new Ejecutar.TRCANCETOTALACTRNI.NROLLAMADAV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCANCETOTALACTRNI.STDAUTORIZAV.ARAUTREMOTAP }
     * 
     */
    public Ejecutar.TRCANCETOTALACTRNI.STDAUTORIZAV.ARAUTREMOTAP createEjecutarTRCANCETOTALACTRNISTDAUTORIZAVARAUTREMOTAP() {
        return new Ejecutar.TRCANCETOTALACTRNI.STDAUTORIZAV.ARAUTREMOTAP();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCANCETOTALACTRNI.STDAUTORIZAV.ARTRNMSJPARMV }
     * 
     */
    public Ejecutar.TRCANCETOTALACTRNI.STDAUTORIZAV.ARTRNMSJPARMV createEjecutarTRCANCETOTALACTRNISTDAUTORIZAVARTRNMSJPARMV() {
        return new Ejecutar.TRCANCETOTALACTRNI.STDAUTORIZAV.ARTRNMSJPARMV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCANCETOTALACTRNI.STDAUTORIZAV.STDTARGETTERMINALV }
     * 
     */
    public Ejecutar.TRCANCETOTALACTRNI.STDAUTORIZAV.STDTARGETTERMINALV createEjecutarTRCANCETOTALACTRNISTDAUTORIZAVSTDTARGETTERMINALV() {
        return new Ejecutar.TRCANCETOTALACTRNI.STDAUTORIZAV.STDTARGETTERMINALV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCANCETOTALACTRNI.STDAUTORIZAV.ARIDSALTADOV }
     * 
     */
    public Ejecutar.TRCANCETOTALACTRNI.STDAUTORIZAV.ARIDSALTADOV createEjecutarTRCANCETOTALACTRNISTDAUTORIZAVARIDSALTADOV() {
        return new Ejecutar.TRCANCETOTALACTRNI.STDAUTORIZAV.ARIDSALTADOV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY.PSVERRORV }
     * 
     */
    public Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY.PSVERRORV createEjecutarTRCANCETOTALACTRNITRCANCETOTALACEVTYPSVERRORV() {
        return new Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY.PSVERRORV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY.PSVIMPAUTV }
     * 
     */
    public Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY.PSVIMPAUTV createEjecutarTRCANCETOTALACTRNITRCANCETOTALACEVTYPSVIMPAUTV() {
        return new Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY.PSVIMPAUTV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY.ACACP }
     * 
     */
    public Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY.ACACP createEjecutarTRCANCETOTALACTRNITRCANCETOTALACEVTYACACP() {
        return new Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY.ACACP();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY.ACVTIPOCOBROV }
     * 
     */
    public Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY.ACVTIPOCOBROV createEjecutarTRCANCETOTALACTRNITRCANCETOTALACEVTYACVTIPOCOBROV() {
        return new Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY.ACVTIPOCOBROV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY.RXACRLACP }
     * 
     */
    public Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY.RXACRLACP createEjecutarTRCANCETOTALACTRNITRCANCETOTALACEVTYRXACRLACP() {
        return new Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY.RXACRLACP();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY.ACRAZONCANCEV }
     * 
     */
    public Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY.ACRAZONCANCEV createEjecutarTRCANCETOTALACTRNITRCANCETOTALACEVTYACRAZONCANCEV() {
        return new Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY.ACRAZONCANCEV();
    }

    /**
     * Create an instance of {@link Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY.ACVFECHAVALORV }
     * 
     */
    public Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY.ACVFECHAVALORV createEjecutarTRCANCETOTALACTRNITRCANCETOTALACEVTYACVFECHAVALORV() {
        return new Ejecutar.TRCANCETOTALACTRNI.TRCANCETOTALACEVTY.ACVFECHAVALORV();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EjecutarResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = mx.babel.arq.comun.constants.ServicioWebConstants.SOAP_PORT_URL_TRN + "TR_CANCE_TOTAL_AC_TRN", name = "EjecutarResult")
    public JAXBElement<EjecutarResult> createEjecutarResult(EjecutarResult value) {
        return new JAXBElement<EjecutarResult>(EJECUTARRESULT_QNAME, EjecutarResult.class, null, value);
    }

}
